### ISSUE TITLE
Basic testing

### ISSUE THREAD

**Issue by bitinn** [karai17/Simple-Tiled-Implementation#101]
Graphical unit testing is probably best done through comparing rendered output with reference output. Luckily, ImageMagick has a [comparison cmd built-in](http://www.imagemagick.org/script/compare.php).

Not sure [Lua binding](https://github.com/leafo/magick) supports it yet, but if you are ok with using another language (since we are just comparing images), a bit of Node.js [with make this super trivial](https://github.com/uber/image-diff).

I haven't figured out how to automate with Travis CI, given actual rendering require LOVE itself. Still, with `love.graphics.newScreenshot` it won't be difficult to generate rendered output for comparison locally.

Anyway, having tests are pretty cool because they ensure bugs can be reproduced and PR are doing what you expect. STI is popular enough, this will set a higher bar :)

PS: I am still new to LOVE and Lua so apologize in advance if I miss out any blocking issue that prevent this from happening.

**Comment by karai17** [comment]
That's a good point. I could create some test maps in Tiled and then render them out in LOVE for comparison with Tiled.

**Comment by bitinn** [comment]
@karai17 yeah that's the idea. I worked with Corona SDK before and Dusk engine (a tilemap rendering library) have some testcases, might be good reference material:

https://github.com/GymbylCoding/Dusk-Engine/tree/master/tests

**Comment by karai17** [comment]
I don't think working with Travis or Node would be terribly helpful in this case. I think it would be easier and more sensible to create a LOVE "game" that simply loads a map, takes a screenshot, and cycles through maps. That way you can run the test and get several screenshots without having to do anything manually, and you will always have updated results.

I can probably set this up in a few hours, once I am off the clock.

**Comment by bitinn** [comment]
sounds good, though you still need to do a bit of image comparison, no? I guess if the map is simple enough comparison by human eye is good enough :)

**Comment by karai17** [comment]
You can design the map in ways that human eye comparison should be easy enough. Using a grid tileset instead of a smooth one, that sort of thing.

**Comment by karai17** [comment]
I added some tests.
