### ISSUE TITLE
STI unable to handle certain filename

### ISSUE THREAD

**Issue by bitinn** [karai17/Simple-Tiled-Implementation#103]
I have a demo to reproduce this (see below). But I am still not sure this is a problem with `zip` on OS X, or LÖVE core or STI.

- If you run this simple example unzipped, everything works.
- If you run this simple example as a `.love`, `STI.new` will report error:

`modules/sti/map.lua:55: Could not open file maps/e_t02_[][][][].png. Does not exist.`

where `[]` is just boxes because default font lacks Japanese glyph support.

While I understand:

- Lua has less than optimal UTF-8
- It's madness to try UTF-8 filename

I do expect this to work because `love.graphics.newImage` seems to work just fine, and STI works when your source isn't zipped.

Renaming all of my assets will take an afternoon, so I am asking, is `formatPath` doing something weird? just `print` before line 54 I don't see any problem. Yet I can't reproduce it with `love.graphics.newImage` alone...

[demo5.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/211178/demo5.zip)

**Comment by bitinn** [comment]
PS: If I can consistently reproduce it with `love.graphics.newImage` alone I would have open an issue on LÖVE core. I do see people facing very similar issue (unfortunately the OP didn't actually solve it). So I wonder if said issue still exists.

ref: https://love2d.org/forums/viewtopic.php?t=79947

**Comment by bitinn** [comment]
Wait, wait, I am seeing something interesting...

Under my OS X Sublime Text, if I copy the filename from Finder, it shows as:

![screen shot 2016-04-09 at 6 55 27 pm](https://cloud.githubusercontent.com/assets/1484279/14403307/af347a6e-fe84-11e5-9073-3b5d7d91527c.png)

But in the `test-1.lua` export from Tiled, it shows as:

![screen shot 2016-04-09 at 6 55 23 pm](https://cloud.githubusercontent.com/assets/1484279/14403326/1a16b73e-fe85-11e5-93da-6b001fd01a7b.png)

Glyph wise, the export Tiled looks more correct, as the proper display is `e_t02_ドア外装`.

BUT, it's exactly the Tiled name causing my problem! I hope this is something we can fix from Tiled end.

**Comment by bitinn** [comment]
For reference:
- https://github.com/bjorn/tiled/issues/1247
- https://bitbucket.org/rude/love/issues/1153/os-x-require-tileset-unicode-filename-to

Seems like there won't be an easy solution to this other than changing my filenames, but personally I prefer fixing it on LÖVE, would be pretty weird for Tiled to export different filenames on different platforms, making collaboration and troubleshooting more difficult...

**Comment by karai17** [comment]
Yeah, there isn't much I can do on my end here. This looks like an issue with OS X more than anywhere else. If Tiled or LOVE were to assist here, it would be a work around because OS X is being stupid.

Is there a particular reason why you don't want to use ASCII names? Would probably save you the most headache in the end.

**Comment by bitinn** [comment]
> Is there a particular reason why you don't want to use ASCII names? Would probably save you the most headache in the end.

I got a few hundred assets with problematic Japanese names, but after finding out this problem, I have bite the bullet and converted them to ASCII.

**Comment by karai17** [comment]
It's a crappy issue, but I'm glad you've been able to work around it. <3
