### ISSUE TITLE
Explain under which scenario is custom layer more desirable

### ISSUE THREAD

**Issue by bitinn** [karai17/Simple-Tiled-Implementation#105]
This is related to #64 

Readme gives an example of putting player on custom layer, but custom layer seems more like a way to do custom rendering outside of tmx spec to me.

I mean, why not add player and npc onto an object layer at runtime, where render order is already well-defined? I am thinking top-down RPG and side-scrolling Platformer...

**Comment by karai17** [comment]
Object layers are for static data, custom layers are for dynamic data

**Comment by bitinn** [comment]
Thx for the reply, but I think a clearer definition for `data` is needed here.

If I have a classic top-down RPG character, which moves around on the map, and the sprite will change to match it's direction of movement, is it dynamic?

If I have items and NPC on the same map, which are mostly stationary, but may animate itself in loops or trigger dialogue boxes/events, are they static?

It seems to me the other reason for not drawing player character on Object layer is performance. But in quite a few instances it would be desirable: imagine you have a scene of gathering, when player character move about, he/she is bound to stand in front or behind a NPC. If Player and NPC are not on the same Object layer, we will have to manage their render order on our own, and possibly have multiple custom layers just so we can put character in the right z-index.

Is this really the intended way of working with Tiled maps?

**Comment by karai17** [comment]
The way that I have STI set up is that you're supposed to use object layers as a sort of schematic where you read the data and create game objects into a custom layer. Objects in Tiled and STI are essentially geometric shapes that serve no practical purpose except to hold data (properties, location, whatever). Using that data, you can then convert it into whatever sort of game object you'd like.

**Comment by bitinn** [comment]
Thx for clarifying that. I searched on Tiled forum and indeed you are right.

- http://forum.mapeditor.org/t/how-should-i-use-an-object-layer/413
- http://forum.mapeditor.org/t/how-to-use-object-and-image-layers/594

So in case of STI, I am supposed to handle the render order of dynamic objects myself within Custom layers (use z and y value to decide render order etc.). And not rely on Object layer's special render rules (which probably just for convenience when you use Tiled GUI).

**Comment by karai17** [comment]
Yeah, grabbing all the objects in your custom layer and sorting them by their Y axis so things closer (bigger number) are drawn last.
