### ISSUE TITLE
Odd number screen resolution sometimes lead to garbled rendering

### ISSUE THREAD

**Issue by bitinn** [karai17/Simple-Tiled-Implementation#106]
aka iPhone 6 resolution (375 × 667 pt).

![screen shot 2016-04-19 at 7 32 41 pm](https://cloud.githubusercontent.com/assets/1484279/14637690/834dd2ea-0665-11e6-9491-52bc701059f4.png)

Screen resolution with even number (376 × 668) doesn't seem to suffer from the problem.

The strange thing: it doesn't happen (or become noticeable) on all maps, only some, even though they have similar tilesets and map dimensions.

**Comment by karai17** [comment]
Are you flooring your draw positions?

**Comment by bitinn** [comment]
I want to say I did because I am usually mindful with this sort of things...

But I fail to reproduce this problem after tuning a few layer related operations recently. I will re-open if it comes up again.

**Comment by bitinn** [comment]
Weird, this problem only happens on iMac but not my Macbook Air, both non-retina, both use the same version of OS X and LOVE.

I can think of only 2 places where I need to floor explicitly, camera position and draw range, they both are. What else should I look out for?

**Comment by karai17** [comment]
Draw position

**Comment by bitinn** [comment]
I am not getting what you mean. None of the tiles in above image are drawn using custom layer/object layer, they are just drawn through tile layers, by calling `Map:draw()` (it accepts no parameters), no additional scale or rotation are applied. Camera translates the map using floored integer.

I fail to find anything on draw position in your api doc or Tiled, `love.graphic.draw()` is the only thing that takes a draw position but how could a sprite in custom layer mess up tiled layers?

**Comment by karai17** [comment]
Sorry, I was half asleep when I wrote that. If your camera (translation) is floored, then it shouldn't be causing weird artifacts like that.

**Comment by bitinn** [comment]
No worries, I did floored the camera position when I move it, I will have to see if it has anything to do with camera creation using non-integer number.

Still it's kinda strange I can only reproduce it on iMac...

ref: https://github.com/vrld/hump/blob/master/camera.lua#L63-L69

**Comment by bitinn** [comment]
I got it now, both `hump.camera` and `gamera` are doing `/ 2` internally, this means we need at least an even number to ensure translation is an integer.
