### ISSUE TITLE
tile layer is inputted to drawTileLayer function as a table containing the layer

### ISSUE THREAD

**Issue by SimLeek** [karai17/Simple-Tiled-Implementation#110]
Loading up a tmx lua file always creates a layer table inside another table, so I had to edit the drawTileLayer function to get my game to work.

Since the function never received anything other than a table, I made a quick fix:

    function Map:drawTileLayer(t)
	    local layer, byTile =
		    t[1] or t.layer,
		    t[2] or t.byTile
        ...
    end

I made a few other changes too, but I'm not sure whether they're necessary in the most recent version of STI anymore.

**Comment by karai17** [comment]
I have never seen this before... You most be doing something weird.

**Comment by karai17** [comment]
Do you have any more information on this, or should I close the issue?

**Comment by SimLeek** [comment]
Oh, sorry, I'm getting pretty busy now.

I had the problem a few months or so, back when I was trying to program a weird game [[repo](https://github.com/SimLeek/the-Open-Source-Pony-Game)]. I coded some huge fix, but it was likely for an earlier version of your code. I'll still post it though:
    
```
function Map:drawTileLayer(t)
	--if type(layer) == "string" or type(layer) == "number"  then
	--	layer = self.layers[layer]
  --elseif type(layer[1]) == "string" then
  --  layer = self.layers[layer[1]]

	setmetatable(t,{__index={byTile=false}})
	local layer, byTile =
		t[1] or t.layer,
		t[2] or t.byTile
	if type(layer) == "string" or type(layer) == "number" then
		layer = self.layers[layer]
	end

	assert(layer.type == "tilelayer", "Invalid layer type: " .. layer.type .. ". Layer must be of type: tilelayer")

	local bw,bh,sx,sy,ex,ey,mx,my
	if not byTile then
		 bw = layer.batches.width
		 bh = layer.batches.height
		 sx = math.ceil((self.drawRange.sx - layer.x / self.tilewidth	- 1) / bw)
		 sy = math.ceil((self.drawRange.sy - layer.y / self.tileheight	- 1) / bh)
		 ex = math.ceil((self.drawRange.ex - layer.x / self.tilewidth	+ 1) / bw)
		 ey = math.ceil((self.drawRange.ey - layer.y / self.tileheight	+ 1) / bh)
		mx = math.ceil(self.width / bw)
		my = math.ceil(self.height / bh)
	 else
		 bw = self.tilewidth
		 bh = self.tileheight
		 sx = self.drawRange.sx-1
		 sy = self.drawRange.sy-1
		 ex = self.drawRange.ex+1
		 ey = self.drawRange.ey+1
		 mx=layer.width
		 my=layer.height
		 --print(bw,bh,sx,sy,ex,ey,mx,my)
	end


	for by=sy, ey do
		for bx=sx, ex do
			if bx >= 1 and bx <= mx and by >= 1 and by <= my then
				if not byTile then
					for _, batches in pairs(layer.batches.data) do
						local batch = batches[by] and batches[by][bx]

						if batch then
							love.graphics.draw(batch, math.floor(layer.x), math.floor(layer.y))
						end
					end
				else
					local tile=layer.data[by][bx]
					if tile then
						local tw=self.tilewidth
						local th=self.tileheight
						if self.orientation == "orthogonal" then
							tx = bx * tw + tile.offset.x
							ty = by * th + tile.offset.y

							origx = tx
							origy = ty

							-- Compensation for scale/rotation shift
							local compx = 0
							local compy = 0
							if tile.sx < 0 then compx = tw end
							if tile.sy < 0 then compy = th end

							if tile.r > 0 then
								tx = tx + th - compy
								ty = ty + th - tw + compx
							elseif tile.r < 0 then
								tx = tx + compy
								ty = ty + th - compx
							else
								tx = tx + compx
								ty = ty + compy
							end
						elseif self.orientation == "isometric" then
							tx = (bx - by) * (tw / 2) + tile.offset.x + layer.width * tw / 2
							ty = (bx + by) * (th / 2) + tile.offset.y
						elseif self.orientation == "staggered" then
							if by % 2 == 0 then
								tx = bx * tw + tw / 2 + tile.offset.x
							else
								tx = bx * tw + tile.offset.x
							end

							ty = by * th / 2 + tile.offset.y + th / 2
						end

						local ts = tile.tileset
						local image = self.tilesets[tile.tileset].image
						love.graphics.draw(image,tile.quad,(bx-1)*bw,(by-4)*bh)
					end
				end
			end
		end
	end
end
```

**Comment by karai17** [comment]
I looked at your code, and I am very confused about what you are doing. What is `byTile`? That doesn't exist in the Lua file exported from Tiled, nor does it exist in the tmx/xml file. `Map:drawTileLayer` take sin a single argument that is either the name of the layer, the index of the layer, or the layer object itself. You are passing in a table with the layer embedded in it, and some `byTile` flag that doesn't exist anywhere else.

Whatever it is you're doing, it is some sort of customisation that isn't within the scope of STI.

**Comment by karai17** [comment]
Oh god... yeah, don't do that. You **NEVER** want to draw individual tiles one at a time. That is a very bad idea as it will slow your game down incredibly. You always want to use batched draw calls (sprite batches, in this case) and those are built right into STI.

**Comment by SimLeek** [comment]
Ooh! I remember! I had a 2.5d game and wanted to draw the same layer both above and below the player.

**Comment by SimLeek** [comment]
Sorry, the problem was on my end. I was implementing weird isometric stuff and only did `byTile` for one layer. I should at least do `byLine` though, now that I think about it.

**Comment by karai17** [comment]
There are much better ways to solve that problem. Instead of drawing individual tiles, you could just have several layers where things can be in front of or behind a player put into object layers, and sort those objects on their Y axis.

You could also throw objects into a quad tree and draw them like that.

**Comment by SimLeek** [comment]
Well, I'm not sure that would work. My game looks like an orthographic view of a 3d scene.

**Comment by karai17** [comment]
In a 2D game, even 2.5D, the Y axis can be used as a pseudo-depth axis. Sorting objects by their Y value gets them listed back-to-front so objects closer to the camera (lower on the Y axis) get draw last (on top).

**Comment by SimLeek** [comment]
Ah, I thought it was all one flat picture. I'll see if I can implement that then. Thanks!

**Comment by karai17** [comment]
Each sprite batch can be classified as "one picture" and terrain should generally be built that way. It's things like trees and fences and whatever that you need to be able to stand in front of, or behind. Those should be placed into the world as objects, not tiles.

**Comment by SimLeek** [comment]
Oh... I'm not sure I'd have any tile layers after that.

**Comment by karai17** [comment]
Things like grassy fields, lakes, rivers, etc are usually something you stand on top of or colliding against, not in front of or behind (unless you are swimming in said lake...) so those should be tile layers. Anything more interactive should be objects.

If literally none of your map is simple terrain, then I'd reconsider even using Tiled/STI and create a custom object batching library.
