### ISSUE TITLE
Bump Error

### ISSUE THREAD

**Issue by KraXarN** [karai17/Simple-Tiled-Implementation#111]
I created a map and some code, loaded it in Löve and everything works fine until I add collision. I take my layer with the sprites I want to collide with and set "collidable" to true, but after loading it up again, I get the error `sti/plugins/bump.lua:43: attempt to call method 'add' (a nil value)` Tried some different ways, including creating an object layer with collision, but get the same error, just on line 61 instead.

**Comment by Bobbyjoness** [comment]
Do you have the bump library installed?

**Comment by KraXarN** [comment]
How do I do that?
I tried just downloading bump and including it, but it did not work

**Comment by karai17** [comment]
You need to create a bump world, and then pass that into `map:bump_init(world)`

**Comment by KraXarN** [comment]
Tried both `world = love.physics.newWorld(0, 0)` and with bump directly `world = bump.newWorld(64)`, but none of those worked

**Comment by karai17** [comment]
are you properly loading the plugins?

**Comment by KraXarN** [comment]
I'm creating the map with `map = sti.new("maps/level.lua", {"bump"})` and I also require bump directly with `bump = require "bump"`

**Comment by karai17** [comment]
```lua
local bump = require "bump"
local sti  = require "sti"

local world = bump.newWorld(64)
local map   = sti.new("maps/level.lua", { "bump" })
map:bump_init(world)
```

**Comment by KraXarN** [comment]
Creating the world after the map was partly the issue, but now I get another error `sti/plugins/bump.lua:100: attempt to call method 'getRect' (a nil value)`

**Comment by karai17** [comment]
Are you doing the following?

`map:bump_draw(world)`

**Comment by Bobbyjoness** [comment]
getRect is a method of the bump world object. Are you sure you initialized
the world correctly?

**Comment by Bobbyjoness** [comment]
Oh karai gots it lol. I forgot about that arg.

**Comment by KraXarN** [comment]
No clue where I got `map:bump_draw(map, world)` from. Removing map fixed it. Everything seems to work now! Thanks!

**Comment by karai17** [comment]
<3 good luck!

**Comment by KraXarN** [comment]
Just noticed that in the documentation it says you should use `bump_draw(map, world)` which doesn't work. Might want to change that :)

**Comment by karai17** [comment]
Yeah, I filed a bug on LDoc that should be fixed in the next version.


---
Landon Manning
lmanning17@gmail.com
