### ISSUE TITLE
Do not use many triangles to represent ellipse

### ISSUE THREAD

**Issue by buckle2000** [karai17/Simple-Tiled-Implementation#114]
![circle](https://cloud.githubusercontent.com/assets/10850402/17197921/baf10f56-5425-11e6-8f87-1a2dec654df3.PNG)
If width = height, use circle shape,
elsewise, use a single polygon for that.

**Comment by karai17** [comment]
Circle shape sucks.

**Comment by karai17** [comment]
Besides, that is a single polygon. It's a triangle fan.

**Comment by buckle2000** [comment]
I don't think so.
https://github.com/karai17/Simple-Tiled-Implementation/blob/master/sti/plugins/box2d.lua#L141
https://github.com/karai17/Simple-Tiled-Implementation/blob/master/sti/plugins/box2d.lua#L33

**Comment by karai17** [comment]
It is worth noting that tileds object are dumb anyway. You really shouldn't
be using them except for maybe the box

**Comment by buckle2000** [comment]
But it does not conflict with the fact that one polygon is better (and faster) than many.
