### ISSUE TITLE
Polylines are drawn as polygons in Box2d debug draw

### ISSUE THREAD

**Issue by buckle2000** [karai17/Simple-Tiled-Implementation#115]
After some tests, I found out actually polylines are converted into `ChainShape`.
But they are drawn as polygons.

**Comment by karai17** [comment]
Is there a difference? This seems to work fine.

**Comment by buckle2000** [comment]
There are different. Sometimes people just need line segments but not a closed figure.

**Comment by Starkkz** [comment]
shouldn't it be a edge shape?

**Comment by buckle2000** [comment]
I mean the debug draw is broken.
