### ISSUE TITLE
Collision boxes offset with bump

### ISSUE THREAD

**Issue by rosshadden** [karai17/Simple-Tiled-Implementation#117]
If I use the box2d plugin, the `box2d_draw` debug method shows the tile collisions where I would expect.  But when using the bump plugin, the `bump_draw` method has all of the collision rectangles offset by exactly `map.tilewidth` and `map.tileheight`.

Box2d:
![2016-08-20-16 09 45](https://cloud.githubusercontent.com/assets/669012/17833644/98b54bd6-66f0-11e6-98c5-d0af37a7540f.png)

Bump:
![2016-08-20-16 10 47](https://cloud.githubusercontent.com/assets/669012/17833647/b185f106-66f0-11e6-9734-286f2e4a762d.png)

Any ideas?

**Comment by karai17** [comment]
@Bobbyjoness ping!

**Comment by Bobbyjoness** [comment]
That's weird. Always worked fine for me. I'll look into it now but I won't be able to commit any changes until I get home from work.

**Comment by rosshadden** [comment]
Thanks!  I'm willing and able to test anything you want me to.  My example is pretty minimal, and all I am changing is a couple strings/methods from `box2d` => `bump`.  Thus I think it's a difference in the plugin files.

**Comment by Bobbyjoness** [comment]
Do you have an offset set in your map file? Maybe the way I calculate the offset messes up the placement.

**Comment by rosshadden** [comment]
No. I have no map offset, layer offset, nor tileset offset.

**Comment by Bobbyjoness** [comment]
I'm not sure if it will help but try changing 

x = x * map.tilewidth + tile.offset.x + map.offsetx

to

x = (x-1)*map.tilewidth + tile.offset.x + map.offsetx 

And the same for y. If that fixes the issue then that means that either at some point the way tiles are numbered were changed or that I never tested that branch of the code lol.

**Comment by Bobbyjoness** [comment]
I can't get you a line number because I'm on mobile. Sorry.

**Comment by rosshadden** [comment]
Yep, that did it.  I'll submit a pull request for it since you're on mobile.

Thanks to both of you!
