### ISSUE TITLE
Global table pollution

### ISSUE THREAD

**Issue by buckle2000** [karai17/Simple-Tiled-Implementation#122]
https://github.com/karai17/Simple-Tiled-Implementation/blob/master/sti/init.lua#L502

**Comment by karai17** [comment]
Whoops! Feel free to send a PR. :)

**Comment by Bobbyjoness** [comment]
You can probably just make it a local variable and submit a pr lol

**Comment by karai17** [comment]
sniped!

**Comment by buckle2000** [comment]
I would not send a PR because I still have last PR closed.

**Comment by karai17** [comment]
fixt
