### ISSUE TITLE
 Map:setDrawRange (transX, transY, w, h) doing nothing

### ISSUE THREAD

**Issue by eduardomezencio** [karai17/Simple-Tiled-Implementation#123]
As far as I understand what the documentation says,  Map:setDrawRange (0,0,100,100) should make only a 100x100 square of the map visible, but this functions does nothing in my tests. The map is always rendered entirely. (and also the first two parameters should translate the map, and they also do nothing)

**Comment by karai17** [comment]
It draws all the sprite batches that touch within 0,0 and 100,100. That could be significantly larger than 0,0 100,100 and might *look* like it's not working.

**Comment by eduardomezencio** [comment]
Now that you explained it I feel like (maybe) I understand it better... Could you explain to me what causes stl to use different batches other than using tilesets from different files?

**Comment by karai17** [comment]
STI batches nearby tiles together to make drawing more efficient. By default, batches are 20x20 tiles in size, but can be bigger. So if your drawrange specifies an area and only a corner of a batch is within that area, the entire batch will draw. In most cases this is not an issue as it just draws off screen, but in some edge cases you may want to actually limit the viewport on screen. In that case, you'll want to also set a [Scissor](https://love2d.org/wiki/love.graphics.setScissor) which actually trims what is drawn.

**Comment by eduardomezencio** [comment]
Thank you very much! I think this exact explanation that you gave me would be very welcome in the documentation, at least for users like me.
