### ISSUE TITLE
box2d: collision objects define in tiles are broken

### ISSUE THREAD

**Issue by antong** [karai17/Simple-Tiled-Implementation#124]
For example, if you define a polygon collision object for a tile, the shape will not be added at the location of the tile instance, but at (0,0). This works better for rectangular objects.

I tried to find an easy fix, but failed as the different coordinate systems are handled differently for objects within tiles and objects in an object layer. The coordinates of a vertex in a polygon in a tile are tileinstance<x,y> + object<x,y> + vertex<x,y>. This info is not retained all the way to where the final coordinates are calculated (getPolygonVertices()), but is mangled in different places for different objects (within tiles/in object layers) and different shapes, rectangle, ellipse, polygon, etc.

**Comment by antong** [comment]
I modified the tests/ortho map to demonstrate the issue in antong/Simple-Tiled-Implementation@fbd3912e5d140cbbc8a8c930034202ba9324d52f . This also includes my failed attempt at fixing.

**Comment by karai17** [comment]
Hm. I'll look into this.

**Comment by karai17** [comment]
If this is still an issue in the latest versions of STI, LOVE, and Tiled, please open a new issue.
