### ISSUE TITLE
Object layers don't sort correctly

### ISSUE THREAD

**Issue by josefnpat** [karai17/Simple-Tiled-Implementation#126]
So, I just noticed something.

This is what the tiled editor does:

![image](https://cloud.githubusercontent.com/assets/646162/20330802/ea750cda-ab66-11e6-9fe2-0dc43902f459.png)

And this is what the `map:drawLayer` function does in Tiled Version 0.17.1:

![image](https://cloud.githubusercontent.com/assets/646162/20330844/1d69fccc-ab67-11e6-899f-0502bfffc5b4.png)

This ticket does not personally effect me as I'm using my own entity system, so it's low priority.

**Comment by josefnpat** [comment]
Ok, since the draw function associated with each object is batched, this did matter to me.

here's my patch:

```diff
diff --git a/src/libs/sti/init.lua b/src/libs/sti/init.lua
index dc4c7c3..44f23d9 100644
--- a/src/libs/sti/init.lua
+++ b/src/libs/sti/init.lua
@@ -472,6 +472,10 @@ function Map:setObjectSpriteBatches(layer)
 	local tileH    = self.tileheight
 	local batches  = {}
 
+	table.sort(layer.objects,function(a,b)
+		return a.y + a.height < b.y + b.height
+	end)
+
 	for _, object in ipairs(layer.objects) do
 		if object.gid then
 			local tile    = self.tiles[object.gid] or self:setFlippedGID(object.gid)
```

**Comment by josefnpat** [comment]
![image](https://cloud.githubusercontent.com/assets/646162/20331258/00a1379c-ab6a-11e6-9a4f-3efc1feaec75.png)

**Comment by karai17** [comment]
This seems like a game-specific setting to me.

**Comment by josefnpat** [comment]
You're right that it's a setting, but wrong that it's a part of my game and not the tmx file I think. My patch wouldn't be enough to handle what tiled can do regardless.

![image](https://cloud.githubusercontent.com/assets/646162/20366687/d8bb4d64-ac11-11e6-8103-51719da1c3eb.png)

versus:

![image](https://cloud.githubusercontent.com/assets/646162/20366717/f36dea68-ac11-11e6-8b65-6e545b2febe2.png)

Can you not repro, or should I try and make something I can share?

**Comment by karai17** [comment]
I don't think my object code takes Drawing Order into account. Tile layers do, but I don't think Object Layers do.

**Comment by karai17** [comment]
should be fixed now
