### ISSUE TITLE
Objects don't flip correctly

### ISSUE THREAD

**Issue by josefnpat** [karai17/Simple-Tiled-Implementation#128]
I don't think the flipping property works:

Version 0.17.1

Editor:
![image](https://cloud.githubusercontent.com/assets/646162/20367281/75eca75c-ac14-11e6-8766-329994d9c36b.png)

Map:drawLayer:

![image](https://cloud.githubusercontent.com/assets/646162/20367314/9d3688dc-ac14-11e6-9d35-43a260d1fed0.png)

Editor (horizontal):

![image](https://cloud.githubusercontent.com/assets/646162/20367340/ac30e60c-ac14-11e6-9bee-41bbb19986fc.png)

Map:drawLayer (horizontal):

![image](https://cloud.githubusercontent.com/assets/646162/20367363/c14aeed4-ac14-11e6-982c-6a6ddee996dc.png)

Editor (vertical):

![image](https://cloud.githubusercontent.com/assets/646162/20367380/d493eae0-ac14-11e6-97b9-8aa1ddfd8f67.png)

Map:drawLayer (vertical):

![image](https://cloud.githubusercontent.com/assets/646162/20367398/e66ce96a-ac14-11e6-91b5-230f9a662c5b.png)

**Comment by josefnpat** [comment]
I'm looking at the Lua export and the tmx file, and I don't even see the flip data... I don't see the horizontal / vertical flip. hmmmm

**Comment by josefnpat** [comment]
Ok, looking at the data, the vertical and horizontal flags are stored in the GID.

Reference: http://doc.mapeditor.org/reference/tmx-map-format/#tile-flipping

This seems to work for me:

```lua
local horizontal = obj.gid,bit.band(obj.gid,0x80000000)~=0
local vertical = obj.gid,bit.band(obj.gid,0x40000000)~=0
```

Not sure if this helps at all.

**Comment by josefnpat** [comment]
Which you do in `Map:setFlippedGID` from what I see.

**Comment by karai17** [comment]
It looks like object tiles aren't properly using the compensate utility function.

**Comment by karai17** [comment]
If this is still an issue in the lastest versions of STI, LOVE, and Tiled, please open a new issue.
