### ISSUE TITLE
Masked color

### ISSUE THREAD

**Issue by matiasah** [karai17/Simple-Tiled-Implementation#130]
I have set a masked color on Tiled, which when it's displayed on Tiled it does look masked (transparent). But for some reason the original color is displayed as a normal tile on STI (it's not masked, thus not transparent).
![real](https://cloud.githubusercontent.com/assets/5008893/21743701/7481af16-d4e6-11e6-9508-f725dbb0a10e.png)
![bug](https://cloud.githubusercontent.com/assets/5008893/21743702/78a5f8c2-d4e6-11e6-911f-fb30b2621308.png)

Probably the background color isn't displaying either.

**Comment by karai17** [comment]
Is this issue now resolved with your PR?

**Comment by matiasah** [comment]
Yes it is, makes sense to close it now.
