### ISSUE TITLE
Objects appear not to be scaled properly

### ISSUE THREAD

**Issue by Nixola** [karai17/Simple-Tiled-Implementation#134]
This one may be my fault. I have an object in an object layer, its image is a 16x16 tile from a tileset. If I set its width and height to 32x32 inside Tiled it will scale, but when drawing it with STI the object will appear normal sized (although, if I make it collidable the collision box is of the correct size).

**Comment by karai17** [comment]
I wasn't aware you could scale tile objects in Tiled. I'll see if I can get this to work properly with batching.

**Comment by ScottHerrmann** [comment]
This looks to be fixed by PR #165
