### ISSUE TITLE
Strange borders at the left bottom side of hex tiles :(

### ISSUE THREAD

**Issue by Winterwolf** [karai17/Simple-Tiled-Implementation#135]
Hi! I don't understand why my game renders incorrect. Here is screenshot:

![Image of Yaktocat](http://i.imgur.com/cwZgfHd.png)

Tell me please, where do these strange borders?

Sources are [here](https://dl.dropboxusercontent.com/u/7329218/fantasyhextiles_v2.zip).

**Comment by karai17** [comment]
So there are two issues here. The first issue is that your export file has the stagger index set to "odd" but the tmx file is set to "even". When I re-export to lua, all the tiles end up in the right place.

For the second issue, I need to investigate further. It looks like there is an issue with the render order...

**Comment by Winterwolf** [comment]
I tried odd and even, nothing chages :/

**Comment by karai17** [comment]
After talking with @bjorn, I have an idea on how to fix the border issue. I'll try to get that pushed to you in an hour or so.

**Comment by Winterwolf** [comment]
Thank you very much!

**Comment by karai17** [comment]
Patching this is gonna have to wait until later today or tomorrow. But I know how to fix this. Basically, Tiled's format for staggered maps interleaves two rows together. To fix the rendering, I need to de-interleave them and draw each row separately.

**Comment by Winterwolf** [comment]
That's good :)

**Comment by karai17** [comment]
Latest commit should fix this!

**Comment by Winterwolf** [comment]
Awesome! :+1: I am very grateful to you, thanks!
