### ISSUE TITLE
Error: Could not open file (image). Does not exist.

### ISSUE THREAD

**Issue by youssefhabri** [karai17/Simple-Tiled-Implementation#138]
Hi, I tried to use STI with one of the maps in tests folder (ortho.lua map)  and it keeps giving me this error:

	Error: libs/sti/utils.lua:51: Could not open file libs.sti.ash_uvgrid01.jpg. Does not exist.
	stack traceback:
		[C]: in function 'newImage'
		libs/sti/utils.lua:51: in function 'cache_image'
		libs/sti/init.lua:100: in function 'init'
		libs/sti/init.lua:46: in function 'sti'
		game/scenes/testing.lua:16: in function 'constructor'
		libs/knife/base.lua:9: in function 'SceneTesting'
		game/scene_manager.lua:25: in function 'change_to'
		main.lua:19: in function 'load'
		[string "boot.lua"]:440: in function <[string "boot.lua"]:436>
		[C]: in function 'xpcall'

**Comment by NixieCat** [comment]
I got the same error. I managed a way to "solve" I just changed the directory of the image - I put in the main folder - and added a sti. in the name of the image.

**Comment by karai17** [comment]
fixt
