### ISSUE TITLE
Support without graphics

### ISSUE THREAD

**Issue by matiasah** [karai17/Simple-Tiled-Implementation#141]
It doesn't make much sense to make this module work without the graphics library but I'll explain my reasons, I'm developing a multiplayer game using STI and the dedicated server doesn't support the graphics module, yet it still uses STI to load the map physics along with the API compatibility.

So you could perhaps have a wrapper on the utils file, of the used functions with a love.graphics.isCreated() check to avoid Lua errors on the server side.

If it's too much time consuming to do that I could start doing it myself in a couple of days.

**Comment by karai17** [comment]
I've thought about this for a while and I would like STI to work in a server situation, but I don't really have the time to do that. If you want to work on that and come up with a nice, clean solution, I'd be willing to accept a PR.
