### ISSUE TITLE
map:setDrawRange() no longer available?

### ISSUE THREAD

**Issue by knuxyl** [karai17/Simple-Tiled-Implementation#147]
map:draw()
map:setDrawRange(5,5,love.graphics.getWidth(),love.graphics.getHeight())

Returns 
attempt to call method 'setDrawRange' (a nil value)

I did a find through sti and could not find setDrawRange. was this removed or am I doing something wrong?

This is my file tree

main.lua
+libraries
-----sti
----------init.lua
----------utils.lua
---------+plugins
---------------box2d.lua
---------------bump.lua

**Comment by karai17** [comment]
that function had been made obselete​ and is no longer available.

**Comment by knuxyl** [comment]
Does that mean that it's now hardcoded into the main library to only draw what is visible on screen?

**Comment by karai17** [comment]
not quite, but everything is in a single batch so it still draws efficiently

**Comment by knuxyl** [comment]
Ok thanks!
