### ISSUE TITLE
scaling error

### ISSUE THREAD

**Issue by emuNAND** [karai17/Simple-Tiled-Implementation#152]
whenever i scale using love.graphics.scale, i get weird lines separating my tiles apart
here is a screenshot of the problem
![problem](https://cloud.githubusercontent.com/assets/22921456/25599760/d1b0b05e-2eac-11e7-9f6d-c0bf00249600.png)

**Comment by karai17** [comment]
When you are drawing the map, make sure you floor the coordinates.

```
local tx = math.floor(player.x) -- or whatever your anchor point is
local ty = math.floor(player.y)
love.graphics.translate(tx, ty)
```

**Comment by emuNAND** [comment]
@karai17 no, my translation is fine, it's just scaling causes these lines

**Comment by karai17** [comment]
Can you send me a .love file?

**Comment by emuNAND** [comment]
@karai17, here it is. if it's any help, i use Fedora Linux and the tileset i use is Cave Story+'s
https://mega.nz/#!J0ZAAajR!mPfN-iMLYT2u3a90p6NL-qi8j8r1tX0bHEXt02nD0tQ
space to zoom out for a little bit, wsad to move

**Comment by karai17** [comment]
It should be fixed now with the latest commit~
