### ISSUE TITLE
attempting to call nil value in init.lua

### ISSUE THREAD

**Issue by liTtle-waNg** [karai17/Simple-Tiled-Implementation#153]
When I try to load the map it says that in sti/init.lua it is attempting to call a nil value in line 44.

**Comment by karai17** [comment]
How are you trying to load your map?

**Comment by liTtle-waNg** [comment]
-- include STI into code
local sti = require "sti"

function love.load()
	-- Load map
	map = sti("/Users/AsianBoyGames/Desktop/level_1_mountain.lua")
end

function love.update(dt)
	--update world
	map:update(dt)
end

function love.draw()
	--drawing the world
	map:draw()
end

**Comment by karai17** [comment]
Lua paths are relative to the current working directory (where you execute Lua). In LOVE's case, this is where main.lua sits. So you need to put your level file somewhere in your game folder and then load it like this:

```lua
map = sti("path/from/cwd/map.lua")
```

**Comment by karai17** [comment]
So if you have an assets folder inside you rgame folder, then you'd do `assets/map.lua`

**Comment by liTtle-waNg** [comment]
I got love2d not to show an error but nothing is showing up on the love2d window. 
`-- include STI into code
local sti = require "sti"

function love.load()
	-- Load map
	map = sti("/Assets/level_1_mountain.lua")
end

function love.update(dt)
	--update world
	map:update(dt)
end

function love.draw()
	--drawing the world
	map:draw()
end`

**Comment by karai17** [comment]
send me a love file

**Comment by liTtle-waNg** [comment]
This is my whole tiny project. 

[platformer.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/988233/platformer.zip)

**Comment by karai17** [comment]
It's drawing fine, you just have a lot of empty space in the top-left corner! If you make a bigger window (or a smaller map...) you will see your map.
