### ISSUE TITLE
1.0 just came out.

### ISSUE THREAD

**Issue by auxiliary-character** [karai17/Simple-Tiled-Implementation#156]
http://www.mapeditor.org/2017/05/24/tiled-1-0-0-released.html

Sounds like there's cool stuff in it.

**Comment by karai17** [comment]
Wow, this does look like a substantial release... I'll have to get this
sorted.


---
Landon Manning
lmanning17@gmail.com

**Comment by auxiliary-character** [comment]
Thanks, famalam. You're the best.

**Comment by ScottHerrmann** [comment]
Will be looking at some of the new updates to Tiled eventually, there are some cool features that were added.

**Comment by lemilonkh** [comment]
I've patched STI for Tiled v1+ support. Do you want a PR?

**Comment by karai17** [comment]
A PR would be awesome. :)

**Comment by davidjtferguson** [comment]
Hello! I'm looking at using STI for a project. The readme still says Tiled version 0.18 - did this PR go in? No worries if not, I'm not sure I'll need the newer features anyways.

**Comment by Bobbyjoness** [comment]
I don't believe a PR was submitted

**Comment by karai17** [comment]
I've received lots of really good PRs that have added 1.0+ features and several bug fixes. I've also added some new features today too. I'll close this as I am looking to make a formal release soon.
