### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by Howld** [karai17/Simple-Tiled-Implementation#163]
I follow the tutorial on http://lua.space/gamedev/using-tiled-maps-in-love and use 4 layers to test code but add custom layer as 8th layer. So I found the index should be <= 5 when nothing draw on the window.

<pre>
    -- Create new dynamic data layer called "Sprites" as the 8th layer
    local layer = map:addCustomLayer("Sprites", 8)
</pre>

**Comment by Howld** [comment]
<pre>
function love.draw()
    -- Translate world so that player is always centred
    local player = map.layers["Sprites"].player
    local tx = math.floor(player.x - love.graphics.getWidth() / 2)
    local ty = math.floor(player.y - love.graphics.getHeight() / 2)
    love.graphics.translate(-tx, -ty)

    -- Draw world
    map:draw()
end
</pre>

No need 'love.graphics.translate(-tx, -ty)'.
'map:draw()' should be 'map:draw(-tx, -ty)'.

**Comment by karai17** [comment]
lua.space doesn't seem to update frequently, even when I've asked for changes. I'll look at porting the tutorial to another website at some point.

**Comment by 132ikl** [comment]
Could you include a updated version of the tutorial in the repository until you port it to a different site? Doesn't need to be anything fancy, a text file or markdown file would be suitable.

**Comment by ScottHerrmann** [comment]
I'll look into updating the Readme.md file eventually, unless @karai17 beats me to it.

**Comment by karai17** [comment]
I moved the tutorial into the repo under `/tutorials` so it should be up to date now.
