### ISSUE TITLE
Error if there's no setColor call before the draw call

### ISSUE THREAD

**Issue by flamendless** [karai17/Simple-Tiled-Implementation#164]
awesome lib. although I want to ask about this particular issue in this snippet:

```lua
function love.draw()
  map:draw()
end
```
The code above will throw an error about 'a' being a nil value. so after checking the code, it seems that 'a' is nil because there is no setColor call before that. 

Is that how it should be? If so, we can assert a better error message about the error and say that a setColor call is needed before calling draw. Or, i think, it would be better if lg.getColor() returns nil, just assume or set 255,255,255,255 as default before the operation.

**Comment by ScottHerrmann** [comment]
I tested this in a clean environment with a working Tiled Map doing only the following

```lua
sti = require'sti'
map = {}
function love.load()
  map = sti("Small_Test.lua")
end


function love.draw()
  map:draw()
end
```
and it worked fine. I'm not sure if there's something I'm missing but I was unable to reproduce this issue.

**Comment by flamendless** [comment]
Sorry, if that map draw function is called from another function beside the love.draw. like:

```
.......
.......

function love.draw()
  stage1.draw()
end

function stage1.draw()
  map:draw()
end
```

**Comment by ScottHerrmann** [comment]
Double check that you're running the current version of STI, as I tested the following code with no issues. If you are then it may be a .tmx issue and I would need your map tiles and tilesets (unless you're using embedded) in order to dive further into it.

```lua
sti = require'sti'
map = {}
function love.load()
  map = sti("debug.lua")
end


function love.draw()
  drawMap()
end

function drawMap()
  map:draw()
end
```

**Comment by karai17** [comment]
Are you using the latest version of LOVE? `love.graphics.getColor()` always returns 4 values, r g b and a. I'm not sure why you would be getting this error unless the version of LOVE you are using is out of date.

**Comment by karai17** [comment]
Closed due to lack of response.
