### ISSUE TITLE
Fix alpha drawing for maps

### ISSUE THREAD

**Issue by LavenderTheGreatGB** [karai17/Simple-Tiled-Implementation#170]
The library seems to suffer from maps loading with black backgrounds, to fix this, I put 'love.graphics.setBlendMode("alpha")' in the main.lua between lines 767 and 768, any chance you could implement the fix in the main branch?

**Comment by ScottHerrmann** [comment]
Double check that you're using an updated version of STI, the main.lua and map.lua files for STI have since been removed. I can try testing this if you are in fact using the current version of STI, though I have a black background set in my maps and am not having issues in my tests.

**Comment by karai17** [comment]
I don't quite understand the issue here. What type of map are you using? Orthogonal? Isometric? Is there black bordering your map that shouldn't be there? Can I see a screenshot?

**Comment by karai17** [comment]
Closing due to lack of response.
