### ISSUE TITLE
 Item must be added to the world before getting its rect.

### ISSUE THREAD

**Issue by christopherdumas** [karai17/Simple-Tiled-Implementation#171]
I'm trying to run a perfectly by-the-numbers bump program, along the lines of
```lua
function love.load()
   ...
   GameState.map = sti("maps/map"..GameState.mapNumber..".lua", { "bump" })
   ...
   GameState.world = bump.newWorld(32)
   GameState.map:bump_init(GameState.world)
end

function love.update()
   GameState.map:update(dt)
   GameState.world:update(dt)
end
```
It appears that (according to the stack trace) the error is occuring in the process up updating `GameState.world`.

<img width="880" alt="screen shot 2018-02-23 at 7 29 08 pm" src="https://user-images.githubusercontent.com/1920151/36625190-dec1ead4-18cf-11e8-8efb-86faf78f003a.png">

Can you guys help me with this? Thanks!

**Comment by flamendless** [comment]
Try updating world first before map

**Comment by christopherdumas** [comment]
okay

**Comment by christopherdumas** [comment]
I get the same error

**Comment by karai17** [comment]
Unfortunately I did not write the bump plugin so I'm not quite sure what would be happening here. Can you provide a .love file?

**Comment by karai17** [comment]
Closing due to lack of response.

**Comment by Ristovski** [comment]
This is because `world:update()` takes an object ID as an argument, instead of `dt` in this case.

**Comment by Weston-Boldt** [comment]
@Ristovski you're a lifesaver lol
i had a similar issue and couldn't figure out what was going on until i saw you're comment
