### ISSUE TITLE
Is it possible to use the collision editor for collision?

### ISSUE THREAD

**Issue by maluramichael** [karai17/Simple-Tiled-Implementation#184]
I created my map on one layer and another tile layer just for collision. All the tiles on the collision layer are a copy of the original one but they are slightly red tinted and have a bunch of collision polygons.

Like this: 
![screenshot from 2018-07-23 22-16-25](https://user-images.githubusercontent.com/1489383/43100642-47239a02-8ec6-11e8-9f02-5531ec0126a9.png)

![screenshot from 2018-07-23 22-17-28](https://user-images.githubusercontent.com/1489383/43100650-4b961eac-8ec6-11e8-9d1d-d8960875f75f.png)

But ingame the polygons are gone and there are only full tiles.

![screenshot from 2018-07-23 22-17-44](https://user-images.githubusercontent.com/1489383/43100724-7f614c8e-8ec6-11e8-88fe-7da022e7db4c.png)

I would like to use this feature instead of creating an object layer and draw every polygon by hand every time.

**Comment by karai17** [comment]
are you using bump or box2d

**Comment by maluramichael** [comment]
Iam using box2d

**Comment by karai17** [comment]
can you post a .love file? this should be working.

**Comment by maluramichael** [comment]
@karai17 sorry that you had to wait.
[collision_test.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/2224365/collision_test.zip)

**Comment by karai17** [comment]
If you are still having an issue with the latest versions of STI and Tiled, please create a new issue.
