### ISSUE TITLE
How to zoom out?

### ISSUE THREAD

**Issue by maluramichael** [karai17/Simple-Tiled-Implementation#186]
I would like to zoom out but when i call `map:draw(0,0,0.5)` the map is just getting smaller. How can i tell the map to draw more tiles when its getting smaller?

![screenshot from 2018-07-25 13-05-45](https://user-images.githubusercontent.com/1489383/43197490-9fbca0be-900b-11e8-9d16-cbc4af8b7480.png)

I thought setDrawRange would work but its deprecated and removed. Do you have an example for this?

**Comment by karai17** [comment]
map.resize

**Comment by maluramichael** [comment]
Nice. Am i right that i should not call this every frame? I created now a function setZoom which sets the camera and rezises the map one time because of heavy fps drops.

**Comment by karai17** [comment]
You only need to call it when you change your scale size. If you are rescalinge very frame, thenyou need to call it every frame. But I would recommend against that in general.
