### ISSUE TITLE
[suggestion] infinite maps!

### ISSUE THREAD

**Issue by ghost** [karai17/Simple-Tiled-Implementation#193]
i get an error when loading an infinite map

```
Error: addons/sti/init.lua:274: attempt to index field 'data' (a nil value)
stack traceback:
        [string "boot.lua"]:637: in function '__index'
        addons/sti/init.lua:274: in function 'setTileData'
        addons/sti/init.lua:239: in function 'setLayer'
        addons/sti/init.lua:117: in function 'init'
        addons/sti/init.lua:47: in function 'sti'
        main.lua:12: in function 'load'
        [string "boot.lua"]:488: in function <[string "boot.lua"]:487>
        [C]: in function 'xpcall'
        [string "boot.lua"]:650: in function <[string "boot.lua"]:639>
        [C]: in function 'xpcall'
```
however, my map.lua filesize is only 176kb.

if i disable infinite map, my map.lua exported file is over 470kb O_o, but it works!
i see the index field of data is under a chunks object.
however, if you got no time, i understand, just a friendly suggestion! great project so far, i'm very new to love2d (coming from godot), just trying this baby out today. loving it! very minimalist and fast

**Comment by karai17** [comment]
Are infinite maps a new feature in Tiled?

**Comment by girng** [comment]
@karai17 yeah. iuno when they were added. but yeah

**Comment by yolstatrisch** [comment]
Infinite maps are a relatively new feature introduced in Tiled 1.1 Alpha 7 where it uses the map is separated in multiple chucks.

Link to the devlog for Tiled 1.1 Alpha 7: https://thorbjorn.itch.io/tiled/devlog/13858/tiled-11-alpha7

**Comment by karai17** [comment]
Infinite maps are now supported!
