### ISSUE TITLE
Graphic transformations not applying

### ISSUE THREAD

**Issue by ollelogdahl** [karai17/Simple-Tiled-Implementation#197]
No transformation is applied to the map:draw() call.
I directly copied your example script (under tutorial), and everything worked fine except scaling and moving (translating).

No errors thrown, nor do i have

**Comment by ollelogdahl** [comment]
I'm executing the program by calling lovec.exe, with my project as target

**Comment by zell2002** [comment]
Are you passing your camera properties to the map:draw() ?
map:draw(camera.x, camera.y, camera.scale, camera.scale)
Im using hump.camera, and I'm doing this:
```
camera:attach()
self.Map:draw(-camera.location.x, -camera.location.y, camera.scale, camera.scale)
camera:detach()
```
Which I'd rather avoid, would like to just draw map at X,Y then move my camera around it?

**Comment by karai17** [comment]
sti always draws at 0,0 but the post of the map you want to draw is passed
in

**Comment by karai17** [comment]
^ that used to be very important due to how I wasmaking sprite batches but I've since changed that and can probably rework the draw code. Feel free to tinker with it and submit a PR if you can make it work a little easier.

**Comment by icecheetah** [comment]
I just wanted to post that I am also having this problem, also even if I copy the end code itself. I even tried updating to the latest version of Tiled to see if that would help.

**Comment by karai17** [comment]
@icecheetah How did you solve it?

**Comment by icecheetah** [comment]
@karai17 Basically I used Canvas and with the sprite issue I used "math.floor" for the offset calculations. Also set the filtermode to "nearest","nearest".

**Comment by karai17** [comment]
If this is still an issue with the latest versions of STI, LOVE, and Tiled, please open a new issue.
