### ISSUE TITLE
Can't figure out how to use the box2d plugin

### ISSUE THREAD

**Issue by antoinePaulinB7** [karai17/Simple-Tiled-Implementation#200]
Basically what the title says. I can't find any tutorials and I'm totally lost. Please help.

**Comment by karai17** [comment]
Have you used box2d (love.physics) before?

**Comment by antoinePaulinB7** [comment]
I've used love.physics independently from box2d and sti, but I fixed the issue. The thing is I was trying to do map:box2d_init(..) in my love.load() but love kept saying box2d_init was a nil. I just scrapped all of sti, and copied it back in the directory and it worked O,o. (Sorry for the vague issue)

**Comment by karai17** [comment]
Very strange. At least you got it working. :)
