### ISSUE TITLE
Map Import throwing error in 11.2

### ISSUE THREAD

**Issue by VickyPhoton** [karai17/Simple-Tiled-Implementation#204]
Hi, I am not able to import the map in the latest master build of sti in love11.2.

But this commit id is working fine. bbb348396992fa24d6820752521203fc08c8cdd6

Thanks

**Comment by karai17** [comment]
Can you share your map with me? I can;t see any reason why a map wouldn;t be loading. Are you exporting it as a lua file?

**Comment by VickyPhoton** [comment]
/Users/vignesh_s1/Projects/lua/love/udemy-platformer/maps/level1.lua
/Users/vignesh_s1/Projects/lua/love/udemy-platformer/maps/platform_tiles.tsx
/Users/vignesh_s1/Projects/lua/love/udemy-platformer/maps/tilemap.tmx
/Users/vignesh_s1/Projects/lua/love/udemy-platformer/maps/tiles_spritesheet.png

@karai17  Hi the above files are all the files needed to reproduce the issue.

Thanks

**Comment by VickyPhoton** [comment]
@karai17  Any updates on the issue. Do you need any help?

**Comment by karai17** [comment]
Sorry, I haven't been able to look into this yet. I'll look into it either later today or tomorrow. Can you share the stack trace with me so I can take a quick look at the code before I get a chance to make a little project file to test with?

**Comment by VickyPhoton** [comment]
Error

libs/sti/sti/init.lua:893: attempt to index local 'tile' (a nil value)










Traceback

libs/sti/sti/init.lua:893: in function 'setFlippedGID'
libs/sti/sti/init.lua:276: in function 'setTileData'
libs/sti/sti/init.lua:240: in function 'setLayer'
libs/sti/sti/init.lua:118: in function 'init'
libs/sti/sti/init.lua:48: in function 'sti'
main.lua:28: in function 'load'
[C]: in function 'xpcall'
[C]: in function 'xpcall'

**Comment by karai17** [comment]
I found the issue. I removed a check to verify that the GID is valid. I misread my code where I am setting `local i = 1` and verifying that `gid > 0`, which I mistook for `i`.
