### ISSUE TITLE
Init.lua throws nil exception

### ISSUE THREAD

**Issue by ThowV** [karai17/Simple-Tiled-Implementation#205]
Hello,

So I've been trying to upgrade to the latest version of sti and tiled but I ran into a problem.
I have a map with multiple layers and an object layer holding an object called Player.
When I try to launch the game I get the following exception: 

Error: helpers/sti/init.lua:278: attempt to index field 'data' (a nil value)
stack traceback:
        [string "boot.lua"]:637: in function '__index'
        helpers/sti/init.lua:278: in function 'setTileData'
        helpers/sti/init.lua:243: in function 'setLayer'
        helpers/sti/init.lua:118: in function 'init'
        helpers/sti/init.lua:48: in function 'sti'
        playstate.lua:26: in function 'new'
        menu.lua:194: in function 'update'
        statemachine.lua:41: in function 'update'
        main.lua:18: in function 'update'
        [string "boot.lua"]:509: in function <[string "boot.lua"]:493>
        [C]: in function 'xpcall'

I am using tiled version 1.2.3 and the latest love and sti versions.

Thanks in advance

**Comment by karai17** [comment]
I am looking at STI's code and `init:278` is simply an `end`. Are you sure you are using the latest version? You may want to check out the code from Github.

**Comment by ThowV** [comment]
I am sure I am using the latest version.
I found that if I use your test map it works fine, so it must mean that there's something wrong with my map. I am comparing our maps and I see no difference at all but I'll keep looking.

**Comment by karai17** [comment]
Did you check out the code from the git repo or did you download sti from somewhere else?

**Comment by ThowV** [comment]
I got the code from your repo

**Comment by karai17** [comment]
Hm.. I am very confused by your error then. `init:278` doesn't make sense to produce that error, I would expect it from `init:275`. Can you send me your maps so I can test them?

**Comment by ThowV** [comment]
It throws it in 275 this time: 
Error: helpers/sti/init.lua:275: attempt to index field 'data' (a nil value)
stack traceback:
        [string "boot.lua"]:637: in function '__index'
        helpers/sti/init.lua:275: in function 'setTileData'
        helpers/sti/init.lua:240: in function 'setLayer'
        helpers/sti/init.lua:118: in function 'init'
        helpers/sti/init.lua:48: in function 'sti'
        playstate.lua:26: in function 'new'
        menu.lua:194: in function 'update'
        statemachine.lua:41: in function 'update'
        main.lua:18: in function 'update'
        [string "boot.lua"]:509: in function <[string "boot.lua"]:493>
        [C]: in function 'xpcall'

I created a new map with a simple grass floor.
[test_map_2.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/2988883/test_map_2.zip)

**Comment by karai17** [comment]
It looks like the issue is that you are using Tiled's "grouped tile layers" feature which STI doesn't currently support. I was not aware of this feature and a while ago, before this feature existed, I had implemented my own similar feature in STI for offsetting maps. If your game doesn't currently need this feature, I'd recommend disabling it for now. If you do need it, you can either switch to my implementation for now or you will have to wait until I can update STI to support this feature, or potentially add support yourself and send a PR.

It doesn't look like a terribly difficult feature to implement (famous last words) and I can make it a priority to get this working for you within the next few days.

**Comment by ThowV** [comment]
Grouped tile layers? I just looked at the documentation and I haven't been using groups, atleast, not that I knew of. How would I disable this feature?

**Comment by karai17** [comment]
I'm unsure, but if you look at the exported lua file you will see that the `data` table has been pushed inside of a `chunks` table with some coordinate info. STI currently only searches for `data` directly in the layer.

**Comment by ThowV** [comment]
So I should just remove the chunks table and leave the data table then?

**Comment by ThowV** [comment]
I also know why this happens. Whenever you create a tmx file tiled asks you for a size. They added an option to have unlimited space, this creates chunks.

**Comment by karai17** [comment]
oooh, i suppose that would do it. the infinite map feature.. i'll have to look into that. for now you will want to disable that i suppose.

**Comment by ThowV** [comment]
I'll disable it for now and wait untill you've pushed a fix. Thanks for the quick response!

**Comment by karai17** [comment]
I just pushed support for infinite maps, please let me know if this solves your issue. I also added a test map to the repo.

**Comment by ThowV** [comment]
It did solve this issue but I got a new error even when creating a new infinite map. This time I get this:

Error: helpers/sti/init.lua:520: attempt to index field 'data' (a nil value)
stack traceback:
        [string "boot.lua"]:637: in function '__index'
        helpers/sti/init.lua:520: in function 'set_batches'
        helpers/sti/init.lua:577: in function 'setSpriteBatches'
        helpers/sti/init.lua:272: in function 'setLayer'
        helpers/sti/init.lua:124: in function 'init'
        helpers/sti/init.lua:48: in function 'sti'
        playstate.lua:26: in function 'new'
        menu.lua:194: in function 'update'
        statemachine.lua:41: in function 'update'
        main.lua:18: in function 'update'
        [string "boot.lua"]:509: in function <[string "boot.lua"]:493>
        [C]: in function 'xpcall'

Thankyou for the quick fix on the infinite map issue. I hope we can resolve this one as well. Here is my map: [map.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/2999672/map.zip)

**Comment by karai17** [comment]
I see what the issue is, I shoudl have it patched momentarily.

**Comment by karai17** [comment]
Should be fixed now. :) The issue was that I had a short circuit that looked something like `local tile = chunk and chunk.data[y][x] or layer.data[y][x]` however `nil` is a valid assignment to `local tile` and the short circuit was trying to pull data from `layer.data` which does not exist in an infinite map. I simply rewrite the short circuit to be in its longer form which is slightly less compact but more explicit.

**Comment by ThowV** [comment]
It's totally fixed now, thank you very much!
