### ISSUE TITLE
Init.lua throws nil exception #2

### ISSUE THREAD

**Issue by ThowV** [karai17/Simple-Tiled-Implementation#206]
Good day again. I am not trying to bother you at all but I came across another bug.
This time I set my level size to 100 by 100 tiles and it didn't generate the chunks we were talking about earlier today, but this time I came across another nil exception. Again, your map worked fine, so I tried an older map but that one too generated the same exact exception:

Error: helpers/sti/init.lua:893: attempt to index local 'tile' (a nil value)
stack traceback:
        [string "boot.lua"]:637: in function '__index'
        helpers/sti/init.lua:893: in function 'setFlippedGID'
        helpers/sti/init.lua:276: in function 'setTileData'
        helpers/sti/init.lua:240: in function 'setLayer'
        helpers/sti/init.lua:118: in function 'init'
        helpers/sti/init.lua:48: in function 'sti'
        playstate.lua:26: in function 'new'
        menu.lua:194: in function 'update'
        statemachine.lua:41: in function 'update'
        main.lua:18: in function 'update'
        [string "boot.lua"]:509: in function <[string "boot.lua"]:493>
        [C]: in function 'xpcall'

This is my map:  [map.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/2989240/map.zip)
I hope this one is solvable, if not I'll just have to wait.

Thanks in advance!

**Comment by karai17** [comment]
I believe I have resolved this in a recent commit. Can you please verify?

**Comment by ThowV** [comment]
Youre right, it's been fixed entirely now!

**Comment by karai17** [comment]
Cool. :)
