### ISSUE TITLE
Map scaling

### ISSUE THREAD

**Issue by ThowV** [karai17/Simple-Tiled-Implementation#209]
Okay last question... possibly. I've updated STI from version 0.4 to the latest version. In version 0.4 I used the following code to scale the map: https://textuploader.com/15vgb

It worked perfectly. Now that I've moved on to the latest version this method does not work anymore and I can't find any documentation on how to scale your map so here's my question: How do I scale the map?

Thanks in advance!

**Comment by karai17** [comment]
The tutorial in the repo should show you the correct way to scale in the
latest version. You want to pass in transform info similar to how love's
graphics APIs tend to work.

map:draw(x, y, sx, sy)
