### ISSUE TITLE
Standard functions not working

### ISSUE THREAD

**Issue by ShadowTheReal** [karai17/Simple-Tiled-Implementation#214]
If i use "love.graphics.translate" or "love.graphics.scale" it wont work on my tilemap
I've also tested if it was my code that was doing this but if i draw a box on the same screen and use scale it works for the box and not for the map

**Comment by karai17** [comment]
`map:draw()` manages its own graphics state so if you want to scale or translate it, you will need to pass in those args to the draw function.

```lua
love.draw()
   -- tx, ty, sx, sy
   map:draw(200, 500, 2, 2)
end
```

**Comment by ShadowTheReal** [comment]
But if i do that once the map has already been drawn once, it does not clear the old map

**Comment by karai17** [comment]
can you give me an example love file?

**Comment by ShadowTheReal** [comment]
Uhm, yeah
[lovegame.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/3078830/lovegame.zip)
Sorry, it says i can't upload .love files, so i'll give you the zip

**Comment by ShadowTheReal** [comment]
Ok, i can use love.graphics.clear() to clear the screen....

**Comment by pauljessup** [comment]
You might want to update the documentation for the scale/transformation stuff- you have it do translate in the draw function, as well scaling x2, and I was going nuts trying to figure out why it wasn't doing either after copying and pasting the examples there
