### ISSUE TITLE
How can I collide two object layer using box2d plugin?

### ISSUE THREAD

**Issue by Vikram1323** [karai17/Simple-Tiled-Implementation#224]
I have set collidable = true in custom properties for both nav and player. 
Is there simple way in STI or do I have to look at love.physics.
![Screenshot from 2019-10-13 19-58-27](https://user-images.githubusercontent.com/38137398/66717209-0e589400-edf4-11e9-8841-2f0e3303a58c.png)

**Comment by karai17** [comment]
sti comes with plugins for both love physics and bump. you probably want to
use bump

**Comment by Vikram1323** [comment]
My example have rectangle but I will change that with polygon and add few more polygons. So that player can move anywhere except polygons or can move on polygons that can also work.
- Is bump.lua good at this
- I checked bump.lua github and  first bullet pointer says "bump.lua only does axis-aligned bounding-box (AABB) collisions. If you need anything more complicated than that (circles, polygons, etc.) give HardonCollider a look."
Please enlighten me and thank you for reply.

**Comment by karai17** [comment]
bump only allows rectangles so if you need other shapes  you need to use
something else

**Comment by Vikram1323** [comment]
Thanks
I'll look into it. If someday you have time please make tutorial on this topic.
