### ISSUE TITLE
Can't Zoom out Past 1.0 Scale

### ISSUE THREAD

**Issue by nanobyte** [karai17/Simple-Tiled-Implementation#229]
Hey! It seems like I can't zoom out past a scale of 1.0. If I do, it still zooms out, but it only renders a shrinking box that goes towards the top left of the screen.

I was thinking I could work around it by keeping the 1.0 scale the most zoomed out, but I can't seem to figure out how to specify how many tiles wide the window should be initially.

Hope I can get some advice. I've poured through the code and it seems like it's setting the scale correctly, basically just native love2d.

**Comment by karai17** [comment]
You need to call map:resize(w, h) within love.resize so that the drawing canvas in sti is adjusted

**Comment by sewbacca** [comment]
Have also problems on zoming inside. With 0.5 zoom the map is smaller, but the rectangle also gets halfed. Intuitivly I would think, that the scale wouldn't affect the draw space.

**Comment by karai17** [comment]
Same answer as above. STI uses an internal canvas for drawing so if you are resizing or rescaling the world you need to call map:resize(w,h) to rescale the canvas.

```lua
function love.resize(w, h)
   map:resize(w, h)
end
```

**Comment by sewbacca** [comment]
Unfortunately that's not what I meant.
This is my workaround:
`map:resize(screen_width / 0.5, screen_height / 0.5)`
`map:draw(0, 0, 0.5, 0.5)`

My point is, why should I resize the the drawing area, when it stayed the same. If my window has a size of the 500x500 and I resize the map to 500x500, why does it draw 250x250 if I scale it by 0.5? Why do I have to set its drawing area to 1000x1000 which should be bigger than my window. This isn't a huge problem though, it's just unintuitive.

**Comment by karai17** [comment]
Well, you shouldn't need to do that. If you initialize your window at
500x500 and then create a map, that map should initialize at 500x500 as
well and scaling the world shouldn't draw only in the top-left corner.

---
Landon Manning
lmanning17@gmail.com
