### ISSUE TITLE
Simple Updating and drawing the map shows the objects cutting off Tiles

### ISSUE THREAD

**Issue by BronzeViper** [karai17/Simple-Tiled-Implementation#230]
![love_OKkC3q90sq](https://user-images.githubusercontent.com/55687227/74963051-13c78a00-5437-11ea-840e-2a3db2defa68.png)

As you can see in the pic. These are where I made the objects for collisions and spawn points. I can hide them alright but it shouldn't be cutting off tiles right?

![GEclyjXMVM](https://user-images.githubusercontent.com/55687227/74963293-7e78c580-5437-11ea-8566-9cdfc715ec61.png)

This the tilemap in Tiled. Maybe is it something I did wrong?

**Comment by karai17** [comment]
set the layer's visibility flag to `false` in tiled. sti just draws ugly shapes for objects so it's usually a good idea to either remove the object layer once you load the necessary data from it, or set the visible flag to false (in tiled or in love, either should work)

**Comment by BronzeViper** [comment]
Well, okay. I thought something was wrong because it didn't appear the way you showed it in your tutorial at lua.space. Guess I'll close this issue.

**Comment by karai17** [comment]
I believe I ended up changing the draw for objects to be simpler because
it's not really meant to be viewed anyway.

---
Landon Manning
lmanning17@gmail.com
