### ISSUE TITLE
[Box2d] Physics object randomly gets stuck on collidable tiles.

### ISSUE THREAD

**Issue by CaptainZidgel** [karai17/Simple-Tiled-Implementation#233]
Using the Box2d plugin, sometimes box2d objects (not Tiled objects) seem to get stuck on flat collidable tile layers when applying force (or linear impulses). It happens randomly with no discernible pattern. Here's an example: https://i.gyazo.com/db07ca427285f25a02c2a72abf1f9436.mp4 I never once stop pressing a key in this gif, although I do switch between left/right keys to avoid flying off my platform.

This sort of 'stuckage' does not occur in "vanilla" box2d on a flat body.

**Comment by karai17** [comment]
This is because each tile object has 4 sides and so where they meet, there can be little hiccups on the corners when you are transfering from one tile to the next. It is recommended to, instead of using per-tile collidables, that you use large rectangles or the likes for full surfaces.

**Comment by karai17** [comment]
I would also recommend using a fixed timestamp instead of using `dt` directly. That will smooth out your physics and make it more consistant.

```lua
local time = 0
local tickrate = 1/60

function love.update(dt)
   time = time + dt
   while time >= tickrate do
      time = time - tickrate
      dt = tickrate
      -- do your game updates
   end
end
```

**Comment by CaptainZidgel** [comment]
Thanks for the dt tip, always struggling with that stuff.

As for the large rectangle surface thing, how would you go about doing that?
Something like adding an object in Tiled then replacing that with a large surface in the code, or is there a Tiled method for creating large surfaces beyond the size of singular tiles?

**Comment by CaptainZidgel** [comment]
Generating a ground object for each like-object in Tiled seems like a good solution. Tiled has a pretty simple rectangle select tool to draw large rectangular objects.

**Comment by karai17** [comment]
aye, just create an object layer, make it collidable, and drop a few big
rectangles in there
