### ISSUE TITLE
box2d_init won't create objects

### ISSUE THREAD

**Issue by iimurpyh** [karai17/Simple-Tiled-Implementation#237]
Trying to use the box2d module, and it seems like nothing gets created by box2d_init - other box2d objects in the same world don't collide and box2d_draw draws nothing.

Relevant code:
```lua
function love.load()
	level = sti("assets/tilesheets/lua/1.lua", {"box2d"} )
	world = lp.newWorld(0)
	world:setGravity(0, 90)
	
	level:box2d_init(world)
end

function love.draw()
	lg.setColor(1, 1, 1)
	level:draw()
	lg.setColor(1, 1, 1)
	level:box2d_draw()
end
```

I've set 'collidable' for the layers I want objects to collide with to true, not sure what else to try.

**Comment by karai17** [comment]
Can you link me a .love file that i can take a look at?

**Comment by iimurpyh** [comment]
[tiles_physics_test.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/4913419/tiles_physics_test.zip)

**Comment by iimurpyh** [comment]
Set gravity to something other than 0 in love.load for the effect to be more obvious

**Comment by iimurpyh** [comment]
I found the issue, Tiled was exporting the .lua to the wrong file so the version of the tilesheet being loaded didn't have the changes I made!
