### ISSUE TITLE
Invisible objects are still rendering.

### ISSUE THREAD

**Issue by 133794m3r** [karai17/Simple-Tiled-Implementation#238]
I have an object type labeled "teleport point" which I'll use to be the point where a player will be warped to if they move through a door and it's visibility is set to false yet STI is rendering it. 

The layer only has that single object on it as I'm just learning tiled and want to keep things simplified.

```
      type = "objectgroup",
      draworder = "topdown",
      id = 5,
      name = "teleport_points",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 2,
          name = "spawn_point",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = false,
          properties = {}
        }
      }
    },
```
![Screenshot at 2020-08-18 22-47-18](https://user-images.githubusercontent.com/599849/90586274-5095f300-e1c6-11ea-9e70-6a8191c0df1e.png)

I can provide the TMX and related spritesheets if needed.

**Comment by karai17** [comment]
Send me a .love file that I can poke around in~

**Comment by 133794m3r** [comment]
[test.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/5099136/test.zip)
There's a zip of the whole directory with the tiled map, the tilesets and my god awful testing code.

**Comment by karai17** [comment]
I just pushed a commit to fix this. I wasn't checking if objects were flagged as visible before checking them; now I am!
