### ISSUE TITLE
Collison information not being registered with Bump

### ISSUE THREAD

**Issue by shingle-bells** [karai17/Simple-Tiled-Implementation#244]
I'm using STI with bump, and for some reason the collision map I made isn't being registered in my game. I've confirmed that the collision data is there in the export, and I am initializing the map through Bump. Is there a step I'm missing?

**Comment by karai17** [comment]
Can you post some of your code here so that I can take a look?

**Comment by shingle-bells** [comment]
Here's my game files, I don't know what could be causing it. The map is initialized in GAME.lua.
[game1.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/5455852/game1.zip)

**Comment by karai17** [comment]
Not sure why but I checked your map and there was no collision data in it. I re-exported it from Tiled and the collision data was then present, though I don't think it's doing exactly what you want it to do. When you set a tile as collidable, it will set the whole tile as a collidable object. From what I am seeing, you probably only want to set the sub-objects within your tiles as collidable.

Another quick note, you're defining a love callback function inside of love.update. You can define it outside of update.

**Comment by shingle-bells** [comment]
How do I export the data in a way that STI can detect? Sorry, I'm new to Tiled and Love2D so I'm a little lost.

**Comment by shingle-bells** [comment]
Nevermind, I figured out I was exporting my *tileset* but not my *map.* I feel like a dumbass, but I figured it out. Thanks for helping me regardless!

**Comment by karai17** [comment]
Glad you got it sorted. :)
