### ISSUE TITLE
Colision coordinate type

### ISSUE THREAD

**Issue by Bissiatti** [karai17/Simple-Tiled-Implementation#245]
In map.love, tiled generate, there are layers. In a layer there's a tree like a data number, tile code. My plan is use this data,  coordinate this tree for detect colision. But a map.layers[3] the STI not informe a data tile. Can you do what I thought?

(I am speaking portuguese, if anyone knows this language helps me more)

**Comment by karai17** [comment]
STI has collision built-in, sort of! In Tiled, give a tile, object, or
layer the "collidable" custom property and a boolean value of "true". Then,
if you import the map into LOVE with either the box2d or bump plugin, the
collisions should work.

local sti = require "sti"
local bump = require "bump"

local world = bump.newWorld()
local map = sti("assets/maps/map01.lua", { "bump" })
map:init_bump(world)

---
Landon Manning
lmanning17@gmail.com

**Comment by marknikora** [comment]
@karai17 map:init_bump call dies - attempt to call method 'init_bump' (a nil value)
my map object is ok - checked output using pprint
using tiled 1.2.x and love 11.x

**Comment by karai17** [comment]
Did you load the plugin with your map?

local map = sti("map.lua", { "bump" })

---
Landon Manning
lmanning17@gmail.com
