### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by konsumer** [karai17/Simple-Tiled-Implementation#250]
I am trying to use STI with [json.lua](https://github.com/rxi/json.lua). I prefer JSON because tiled supports it directly, so I don't need to save the TMX and also export to lua. I like just having the 1 source-file, I use directly.

First, I make a map in tiled, inline the tilesets, and save it as JSON.

Then I do this:

```lua
local m = json.decode(love.filesystem.read("assets/maps/level1.json"))
map = sti(m, { "box2d" })
```

Hoping it would work, and I think it's close to the same format as the lua-object.

I get this error:

```
Error: lib/sti/utils.lua:195: Could not open file ../tiles/LPC Terrain/terrain.png. Does not exist.
```

I'm pretty sure I need to somehow set the path, since STI doesn't know where relative paths are (because it's an object instead of a filename) and I don;t see a good way to set `map.dir` before parsing it. Is there a way to do this? If not, would you consider a PR to allow setting it? Or maybe just export `Map` so I can do this in my own function:

```lua
map = setmetatable(json_object, Map)
map:init('assets/map/')
```

Simplest might just be adding another param to `new()`:

```lua
local function new(map, plugins, ox, oy, dir)
	dir = dir or ""

	if type(map) == "table" then
		map = setmetatable(map, Map)
	else
		-- Check for valid map type
		local ext = map:sub(-4, -1)
		assert(ext == ".lua", string.format(
			"Invalid file type: %s. File must be of type: lua.",
			ext
		))

		-- Get directory of map
		dir = map:reverse():find("[/\\]") or ""
		if dir ~= "" then
			dir = map:sub(1, 1 + (#map - dir))
		end

		-- Load map
		map = setmetatable(assert(love.filesystem.load(map))(), Map)
	end

	map:init(dir, plugins, ox, oy)

	return map
end

function STI.__call(_, map, plugins, ox, oy, dir)
	return new(map, plugins, ox, oy, dir)
end
```

After doing this, I got `Error: lib/sti/init.lua:195: bad argument #1 to 'pairs' (table expected, got nil)`, so maybe there is more tht needs to be done with it.

**Comment by konsumer** [comment]
Another approach I thought of is to make an STI plugin that can load other file-types,  but the plugin-system doesn't seem to allow overwriting `new`, either.

Maybe this would be best?:

```lua
local sti = require "sti"
local sti_json = requiure "sti-json"

map =  sti(sti_json("maps/level1.json"))
```

where `sti_json` parses the JSON into a table and pre-resolves all the image-paths.

**Comment by karai17** [comment]
loading json files isn't a particularly useful feature. tiled exports Lua
files and that is the fastest way to load your maps. consider your json
files as "project" files and Lua files as "distributable" files.

**Comment by konsumer** [comment]
> loading json files isn't a particularly useful feature

It's useful for me, in the sense that I don't need to have a separate step to export the maps, and they don't get out of sync. The outputted filesize is about the same (maybe a little smaller with JSON or TMX) so really it just cuts down on the duplication in the source of my game, where I need to include a file that can be opened in tiled directly, anyway.

Anyway, I have a path forward, I think. Thanks for the excellent STI, and also including the ability to pass it a table instead of just lua filename.

**Comment by konsumer** [comment]
I started work on this at [sti-json](https://github.com/notnullgames/sti-json), but it's just a stub for now. I will close this issue. Thanks for taking a look.

**Comment by karai17** [comment]
plugin, pr, etc~
