### ISSUE TITLE
Question about STI

### ISSUE THREAD

**Issue by MasterBroNetwork** [karai17/Simple-Tiled-Implementation#252]
Is it possible to use STI to make a building system with Tiled for a sandbox-style game?

**Comment by karai17** [comment]
I don't see why not. sti is largely just a render tool so you should be
able to do what you need with it~

**Comment by MasterBroNetwork** [comment]
Thanks for helping @karai17.
Also, Amazing implementation of Tiled.

👍

**Comment by MasterBroNetwork** [comment]
Just to ask, is there any way to export the changed map after changing it in the live game with the functions?

**Comment by karai17** [comment]
There is currently no way to do that, but I wouldn't be opposed to an export plugin.

**Comment by MasterBroNetwork** [comment]
Ah right, thanks for telling me!
