### ISSUE TITLE
Some questions about STI

### ISSUE THREAD

**Issue by MasterBroNetwork** [karai17/Simple-Tiled-Implementation#253]
How does setLayerTile work?
I can't get it to use the map layer that tiles are on.

Also, would this function modify the actual file that the map uses and save when I close the game?
If not then where would you recommend to look to learn how STI loads maps and the data so I can try and code a save system for my map?

**Comment by karai17** [comment]
`setLayerTile(layer, x, y, gid)` will replace the tile located at the `x,y` location specified with the tile that contains the `gid` you specify. you will need to pass in the actual layer table, not just a name or index of the layer.

```lua
local layer = map.layers["Some TIle Layer"]
map:setLayerTIle(layer, 5, 7, 1234)
```

STI does not affect your files in any way. If you need to create a modified map, you may need to write a plugin to do that. I suppose a simple way to go about that would be to convert the map data to json and store the string somewhere, then load the original map and overwrite the loaded data with the loaded json data so you still have access to functions and the likes.

**Comment by MasterBroNetwork** [comment]
Thank you for the help, I was very confused with the layer part. 👍
