### ISSUE TITLE
Attempt to index local 'tile' (a nil value)

### ISSUE THREAD

**Issue by Lucky4Luuk** [karai17/Simple-Tiled-Implementation#256]

**Comment by Lucky4Luuk** [comment]
Sorry for that, meant to hit backspace instead of enter.

Here's the full error:

```
Error

sti/init.lua:1014: attempt to index local 'tile' (a nil value)


Traceback

sti/init.lua:1014: in function 'setFlippedGID'
sti/init.lua:320: in function 'setTileData'
sti/init.lua:274: in function 'setLayer'
sti/init.lua:124: in function 'init'
sti/init.lua:48: in function 'sti'
asset_loading/map.lua:6: in function 'new'
main.lua:19: in main chunk
[C]: in function 'require'
[C]: in function 'xpcall'
[C]: in function 'xpcall'
```

My tileset is extremely basic. I'm not using an infinite map, I don't use grouped layers. All I did was add an extra layer to my map, a regular layer with tiles, and this started happening.

Let me know if you need anything else :)

**Comment by karai17** [comment]
If you have a love file i can look at, that'd help.

**Comment by Lucky4Luuk** [comment]
[the_game.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/6144572/the_game.zip)
Here's a zip, was just messing around with learning pixel art as I bought aseprite 4 days ago :)

**Comment by karai17** [comment]
What version of Tiled are you using? I have 1.3.1 installed and I just re-exported the  map and it worked.
