### ISSUE TITLE
Trying to take polygon objects from STI and create HardonCollider polygons with them

### ISSUE THREAD

**Issue by BradFitz66** [karai17/Simple-Tiled-Implementation#264]
I'm trying to create colliders via polygon objects in Tiled and I can't seem to do it correctly.

I loop through all objects and get their vertices and then create HardonCollider polygons from them, but when drawing the colliders they are in the wrong positions. I can't figure out where I'm going wrong.

My code:
```
if(object.polygon) then
    local collider={}
    for _, vertice in pairs(object.polygon) do
        local v = vector.new(vertice.x,vertice.y)
        v.x=v.x+(object.layer.x+object.x) -- Trying to add the object's position to each vertex doesn't fix it. Doesn't work without it either.
        v.y=v.y+(object.layer.y+object.y)
        table.insert(collider,1,v.x)
        table.insert(collider,1,v.y)
    end
    local hc_poly=collider_world:polygon(unpack(collider))
    table.insert(colliders,1,hc_poly)
end
```

What am I doing wrong? Do I need to change something about the vertices before using them?

**Comment by karai17** [comment]
If I recall, Tiled's vertices are relative to the object's position, so you'd need to add that to each vertex.

https://github.com/karai17/Simple-Tiled-Implementation/blob/master/tests/objects.lua#L180-L197

**Comment by BradFitz66** [comment]
> If I recall, Tiled's vertices are relative to the object's position, so you'd need to add that to each vertex.
> 
> https://github.com/karai17/Simple-Tiled-Implementation/blob/master/tests/objects.lua#L180-L197

This is already what I'm doing in the code I posted, 

> v.x=v.x+(object.layer.x+object.x) -- Trying to add the object's position to each vertex doesn't fix it. Doesn't work without it either.
> v.y=v.y+(object.layer.y+object.y)
