### ISSUE TITLE
In love2d when I am testing, it says that it does not support tile collections and I will need to make a tile altlas

### ISSUE THREAD

**Issue by Masked-Idiot** [karai17/Simple-Tiled-Implementation#266]
[help.zip](https://github.com/karai17/Simple-Tiled-Implementation/files/8308253/help.zip)
Can someone please fix this.

**Comment by karai17** [comment]
sti does not support tile collections. you will need to stitch together your tiles into a single image rather than many images.

**Comment by 5H2** [comment]
> what does this mean? How would I do this? I am new to lua, do you have a good video? thanks!

**Comment by karai17** [comment]
You need to import them all into photoshop and build a single image out of them, or use some tile atlas building software.

**Comment by 5H2** [comment]
Video? I'm sorry im very new and I don't know how to do anything, what do I do after making the texture atlas?

**Comment by karai17** [comment]
Create a tileset with it in Tiled and use that to build your map. I don't have any videos on hand, but it's fairly straight forward. Basically, instead of using a bunch of images to create your map, you combine them all into 1 image and use tiles from that image to place onto your map (hense the name Tiled or tilemaps).

**Comment by GabrielReyes136** [comment]
> Create a tileset with it in Tiled and use that to build your map. I don't have any videos on hand, but it's fairly straight forward. Basically, instead of using a bunch of images to create your map, you combine them all into 1 image and use tiles from that image to place onto your map (hense the name Tiled or tilemaps).

this is the checkbox that solved the problem for me
![aaawtf](https://user-images.githubusercontent.com/49967790/161347926-168485ae-6da2-465d-a299-14e567ecd480.png)

**Comment by dwexel** [comment]
I got this error even when I had used a single tile atlas. It solved the issue when I embedded the tileset into the map in Tiled. (I think that Tiled recently switched to not embedding the tileset by default.)

**Comment by Masked-Idiot** [comment]
I fixed it. I had just forgot to make it a tileset
