### ISSUE TITLE
How to actually "require" sti.lua

### ISSUE THREAD

**Issue by Jacinto73** [karai17/Simple-Tiled-Implementation#275]
Hi, I I'm new to GitHub, new to programming, new to ALL of this so I'm sure my question will seem inane but I've been at it for hours and still completely baffled.
All I want to do is use require to include the STI module as in the examples. But I can't find an actual sti.lua anywhere. Even under the actual STI directory there's a plugins dir, atlas.lua, graphics.lua, init.lua, and utils.lua. But in all the examples & the tutorial it simply says require sti at the top.
I don't know how to "clone repositories" or even what that means. Usually when I come here, there's a file I need and I just download it and move on with my life.
I apologize for having to ask something that must seem obvious to you all, but could someone please take a moment to tell me what  I'm doing wrong? Would really appreciate it.

Thanks

**Comment by karai17** [comment]
in the lua world, lua typically searches for `sti.lua` and `sti/init.lua`.
you can download sti as a zip file from github and then extract the `sti`
directory into your game directory and then `require "sti"` should find it.
if you put the `sti` directory in a subdirectory such as `libs`, you would
instead `require "libs.sti"`

hope that helps!

**Comment by Jacinto73** [comment]
Okay, I THINK I have it now. Or, at least, I'm getting different errors now. Thanks so much for the reply. Back to working on the tutorial now...

**Comment by karai17** [comment]
if you need any more help, feel free to join the moonscript discord, lots
of folks there who are able to help with love, lua, etc~

https://discord.gg/utjDZRRQ
