### ISSUE TITLE
Error attempt to index local 'layer' (a nil value)

### ISSUE THREAD

**Issue by MexaFoxesStudios** [karai17/Simple-Tiled-Implementation#278]
Error

libreries/sti/init.lua:926: attempt to index local 'layer' (a nil value)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
libreries/sti/init.lua:926: in function 'drawLayer'
main.lua:75: in function 'draw'
[love "callbacks.lua"]:168: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by karai17** [comment]
The area of the code that this error occurs in is for drawing map layers, but the error suggests that you are not providing a layer to be drawn. Can I see the code you wrote that produces this error?
