### ISSUE TITLE
No autocompletion with lua language server for maps

### ISSUE THREAD

**Issue by LemonBreezes** [karai17/Simple-Tiled-Implementation#280]
Hi. So I'm writing this code:
![image](https://github.com/karai17/Simple-Tiled-Implementation/assets/29102529/4cdce682-1b69-4166-b9aa-a35c601465a2)
and I notice there is no autocompletion when I type `MAP:` or `MAP.` in Emacs nor in `vscodium` with the Lua Language Server. Chatgpt tells me that's because Lua is dynamically typed and so the language server cannot infer a return type for `sti()` from the code. But, is it possible to work around this with some kind of type annotation of something?

**Comment by karai17** [comment]
This is a general limitation of Lua. There are some addons that provide
type info for large projects such as love, but they are maintained manually.
