### ISSUE TITLE
error

### ISSUE THREAD

**Issue by verydeaad** [karai17/Simple-Tiled-Implementation#282]
so i'm using a camera extension and trying to draw layers gives me this error
Error

libraries/sti/init.lua:926: attempt to index local 'layer' (a nil value)

i dont know if it's a problem of mine i tried making multiple projects but the same exact message appeares and i can't find a sulotion my own self since it's my first day of using love2d so i couldn't even understand whatever anything meant so help would be appreciated

full error 
Error

libraries/sti/init.lua:926: attempt to index local 'layer' (a nil value)

Traceback

[love "callbacks.lua"]:228: in function 'handler'
libraries/sti/init.lua:926: in function 'drawLayer'
main.lua:45: in function 'draw'
[love "callbacks.lua"]:168: in function <[love "callbacks.lua"]:144>
[C]: in function 'xpcall'

**Comment by karai17** [comment]
can you zip up your project and send it to me so i can take a look?

**Comment by verydeaad** [comment]
wow i tried to make another map since i was going to send you the zipped file and removed the other 3 maps that i tested using and the "another map" worked somehow 
sorry for the inconvience
thank you for your extension though, helped me out alot

**Comment by verydeaad** [comment]
nevermind. guess what, once i try to draw more than one layer, it reports the same error 
while trying to do map:drawLayer(["ground"]) it worked perfectly
but i need more than 1 layer so i tried to draw the rest of the layers i needed but it gives me the error in the earlier comment
zipped file :
https://1drv.ms/u/s!AoCmkwb02xJ3gjN6QjsxfijUh8AT?e=ppBFSp

**Comment by karai17** [comment]
`map:drawLayer(map.layers["tile"])`

that layer name does not exist. in your `map.lua` file, there are only the following layers:

1. ground
2. layer needed tiles
3. trees, objects2
4. trees, objects

**Comment by verydeaad** [comment]
my bad, sorry for your time, still thanks for making sti
