### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by karai17** [karai17/Simple-Tiled-Implementation#64]
While the documentation explains how to use the API, it doesn't explain how to use internal data. Some improvements that could be made are:
- Explain how map.layers works
- Explain Tile Objects from map.tiles and map.layers[y][x]
- Explain how to get properties from map.tiles and map.layers

**Comment by bitinn** [comment]
Also worth noting in doc, `TileLayer.data` is a sparse 2-dimensional array, so `for` loop may not work as you expect.

**Comment by grandmasterhack** [comment]
Is it possible to add examples of what is returned? For example:
`getTileProperties (layer, x, `y)`
If I call the above function & it returns a table how supposed to know what's actually in it?

**Comment by karai17** [comment]
Tile properties :p but sure, i can do that.

**Comment by Bobbyjoness** [comment]
The names and documentation are pretty good at describing what would each function does. In the case of getTileProperties as the name implies it gets the properties table for the tile. Properties table being the properties you set in tiled for each tile.
