### ISSUE TITLE
Requires canvas

### ISSUE THREAD

**Issue by Positive07** [karai17/Simple-Tiled-Implementation#67]
This should be stated in the documentation or somehow add a way to support computers without canvas support (which I would really appreciate hahaha)

**Comment by karai17** [comment]
What video card do you have? LOVE 0.10 is going to have a minimum OpenGL requirement of 2.1 and I suspect virtually every card that supports OpenGL 2.1 will also support canvases.

**Comment by Positive07** [comment]
Inten GMA 3150... Yeah! I'm dying here!

**Comment by karai17** [comment]
Yeah, my best advice would be to try to upgrade to a cheap nvidia or amd card that supports OpenGL 2.1+
