### ISSUE TITLE
Installation Help - Setup Tutorial in the Documentation Needed.

### ISSUE THREAD

**Issue by ImFalling** [karai17/Simple-Tiled-Implementation#69]
While this is not an issue, it is a question.

I probably come off sounding really stupid, but how do I actually go about installing the library?
I download the raw zip from github, because that's the only link available, and then I add it to my project's folder. However, while calling sti (local sti = require("sti")), nothing happens, because there's no STI file in the zip.

Is there a process to go through, or am I missing something?
I'd recommend some form of setup tutorial in the documentation for the future.

**Comment by karai17** [comment]
Lua has a series of places it looks for a file or folder when you use require. First Lua searches for the exact location and file, in this case, sti.lua. If it cannot find that, it then assumes that it is a folder and searches for sti/init.lua. You will notice that there is an init.lua file, so what you need to do is unzip the raw contents you downloaded into some folder and require that folder.

I hope that helps!

**Comment by ImFalling** [comment]
I see now! Thanks a bunch!
