### ISSUE TITLE
convertScreenToTile() should return 1-based index

### ISSUE THREAD

**Issue by martincohen** [karai17/Simple-Tiled-Implementation#70]
Hello, first thanks for the STI, it has saved me a lot of time already.

I found method `convertScreenToTile()` to be a bit inconsistent with 1-based index nature of Lua. it returns 0-based indexes, so I need to +1 them to get to the tile data. Is this intentional? Am I missing something?

Keep up the good work, mister.
--M.

**Comment by karai17** [comment]
The convert functions allow for decimal precision so that you can now how far into a tile your mouse (or whatever) is. The simplest way to get the whole tile number for indexing purposes is to use math.ceil on the returned x and y values.

```lua
local mx, my = love.mouse.getPosition()
local tx, ty = map:convertScreenToTile(mx, my)
tx = math.ceil(tx)
ty = math.ceil(ty)
```

**Comment by martincohen** [comment]
Well, except for when mx is 0, math.floor(cx) + 1 does the trick better. Anyway, thanks for the answer! Great job on STI!
