### ISSUE TITLE
custom properties?

### ISSUE THREAD

**Issue by brod** [karai17/Simple-Tiled-Implementation#71]
It'd be nice to be able to query for custom properties similar to collidable but for interaction or something. Let's say you make a new layer, add a single tile and add the **chest = 001** property, then query it's x,y position with something like

    map:layers[chest].getX()

This would only really work for single tile per layer situations, but if sti supported multiple tileset's or terrain information this could be quite handy for static content. I'll look more closely tonight and try understand how it all works

**Comment by karai17** [comment]
STI supports custom properties.

local tile = map.layers["Layer 1"][y][x]

tile.properties.some_property


---
Landon Manning
lmanning17@gmail.com
