### ISSUE TITLE
A Problem with map.init()

### ISSUE THREAD

**Issue by petidecember** [karai17/Simple-Tiled-Implementation#72]
Hi, im using ZeroBrane Studio IDE with the latest love2d 64-bit and I have some problems upon trying 
```lua
map = sti.new("resources/maps/playground")
```
it throws 
```
STI/map.lua:112: in function 'init'
STI/init.lua:61: in function 'new'
main.lua:4: in function 'load'
[string "boot.lua"]:418: in function <[string "boot.lua"]:413>
[C]: in function 'xpcall'
```
My folder structure looks like this:

1. resources
   * graphics (images for the map as png)
   * maps (the map is exported as lua)
2. STI
3. main.lua
4. conf.lua

My main.lua contains this:
```lua
local sti = require "STI"

function love.load()
    map = sti.new("resources/maps/playground")
end

function love.update(dt)
    map:update(dt)
end

function love.draw()
    map:draw()
end

function love.resize(w, h)
    map:resize(w, h)
end
```

What could be the problem? :S Or maybe i should just downgrade? If yes, how so?
By the way i also tried the Orthogonal example updated to 0.9.8, it works fine, interestingly enough

print(sti.version) 

prints out *nil*

**Comment by karai17** [comment]
Can you send me a .love file?

You should be using sti._VERSION now.

**Comment by petidecember** [comment]
@karai17
https://copy.com/6ZyuLEKWzJEJV704

**Comment by karai17** [comment]
STI doesn't currently support tile collections. You will need to bake all of your tiles into a tile atlas.
