### ISSUE TITLE
attempt to concatenate field `image` (a nil value)

### ISSUE THREAD

**Issue by alandao** [karai17/Simple-Tiled-Implementation#73]
Hi, I'm trying to get the latest version of STI working with LOVE 0.9.2 and I get "attempt to concatenate field `image` (a nil value)" everytime. I think it's related to the filepath of my tiles, but I haven't had any success so far. In tiled, I am not using one picture as a tileset, but a picture for each tile.

http://puu.sh/id90V/e6366688a0.png

**Comment by karai17** [comment]
Sti does not support tile collections. You will need to combine them into a
tile atlas.

**Comment by karai17** [comment]
I've added an error message that better explains this issue in STI. Hopefully I'll add this feature at some point...!
