### ISSUE TITLE
Error in map.lua - attempt to compare number with nil

### ISSUE THREAD

**Issue by ImFalling** [karai17/Simple-Tiled-Implementation#75]
Hello,

So I was using your tool a while back, and returned to it today. However, upon trying to load a map, I'm presented with this error primarily:

http://puu.sh/jNcg3/d06250df7c.png

Simple enough, just remove .. from "../Tileset.png".
After fixing that however, I'm presented with this error:

http://puu.sh/jNcih/355eab7e38.png

Here's my hierarchy, pretty empty at the time, trying to get the map to load (I put the Tileset in all folders, in case there was any confusion there)

http://puu.sh/jNcI5/061fa38be8.png

Error is presented when executing this:

map = sti.new("map2.lua")

That's about it, thanks for your help and your awesome tool!

**Comment by ameyp** [comment]
STI doesn't seem to support Base64-encoded tile layer formatted maps. Changing the Tile Layer Format (via Map -> Map Properties) works.

**Comment by ImFalling** [comment]
Ah, thank you. That helped!

Thanks a bunch!

**Comment by ameyp** [comment]
@karai17 Would you like a PR with support for base64-encoded (uncompressed) maps?

**Comment by karai17** [comment]
@ameyp I load in the lua as Lua instead of as text but if you can get it to work that'd be cool.
