### ISSUE TITLE
Bad argument #1 to 'setfenv' (number expected, got nil)

### ISSUE THREAD

**Issue by giantofbabil** [karai17/Simple-Tiled-Implementation#84]
EDIT: just noticed that I left out the top comment of my code when I pasted to gist so the error is on line 18 in my code but on the gist it shows on line 15, sorry

Trying to set up STI for my new project and I got this error:

Bad argument #1 to 'setfenv' (number expected, got nil)

Traceback

[C]: in function 'setfenv'
sti/init.lua:40: in function 'new'
main.lua:18: in function 'load' (line 15 on gist)
[C]: in function 'xpcall'

Before this line 18(line 15 on gist) of my main.lua had the code:

    --load a map exported to lua from Tiled
    map = sti.new('assets/maps/map01.lua'), {'box2d'}

But I took out the 'assets' it because I was getting an error that said it couldn't find my tileset in 'assets/assets/' and that's when I started getting this new bad argument #1 error.

Here is my code now: https://gist.github.com/giantofbabil/250b3c47ecac25411e8d

**Comment by karai17** [comment]
the relative path to your tileset is different from how you saved it in tiled. you need to use the same relative file structure when saving and loading.

**Comment by giantofbabil** [comment]
Thanks a lot my first time using Tiled, didn't even think about how I changed around some organization in the folders after saving it. Remade map and it loads fine now :)

**Comment by giantofbabil** [comment]
I am now having trouble getting my sprite to draw, or at least it's not on the screen, sorry to bother you I'm new to platformers

**Comment by karai17** [comment]
If you are drawing the sprite outside of the map, you must draw it last. The order in which you draw things is important in 2D.

If you are trying to draw it in the map, check out the readme for some exacmple code, or the demo on the love forum thread for a working example.
