### ISSUE TITLE
Improperly loading flipped tile objects?

### ISSUE THREAD

**Issue by lulublululu** [karai17/Simple-Tiled-Implementation#92]
When loading a tile object, the tilesheet ID seems to become garbled, unless it's some kind of numerological indication of the tile being flipped? Either way it's not documented.

In my case, a tile which should've been indexed as entry 338 on the tilesheet is being read (via object.gid, which itself is a piece of information I kind of stumbled across) was loaded in as 2147483987, and Object doesn't seem to hold any other data which might help in working around this.

Thank you for all your work, this library's been a lovely help in my project so far.

**Comment by karai17** [comment]
Tiled uses bitwise operators within the tile ID to determine flipped flags,
as you expected. The top 3 most significant bits. There is some code in STI
that checks for these flags that you can grab if you need it elsewhere. The
flipped IDs are also added to the Map.Tiles table so they should be there.


---
Landon Manning
lmanning17@gmail.com

**Comment by lulublululu** [comment]
Alright, got it taken care of. Thanks a bunch!
