### ISSUE TITLE
Modifying tiles at runtime

### ISSUE THREAD

**Issue by technomancy** [karai17/Simple-Tiled-Implementation#94]
Maybe this is already possible and I've missed it from reading the docs and code, but I couldn't figure out how to remove a tile from a non-custom layer at runtime. It's easy enough to just do this:

```lua
map.layers[n].data[y][x] = nil
```

But this seems to have no effect. My guess is that the batching optimizations make it so that changes to the `data` table are ignored after the map is loaded, but I'm not sure.

Is this something that's currently possible to do, or does a layer have to be a custom layer in order to change after load time?

**Comment by karai17** [comment]
You need to grab the tile out of the sprite batch and modify that.

**Comment by technomancy** [comment]
Thanks. I am trying to do that, but according to https://love2d.org/wiki/SpriteBatch there is no method to remove a sprite once it's added. Supposedly the `set` method can fake it by using 0 as all its args, but it doesn't actually work when I try it:

```
function destroy_tile(tile)
   for _, t in ipairs(map.tileInstances[tile.gid]) do
      if id == tile.id then
         batch:set(tile.id, 0, 0, 0, 0, 0)
      end
   end
end
```

I'm sure there's something I'm doing wrong, but since none of this is documented I have no way of knowing what it actually is. I'd appreciate a hint.

**Comment by technomancy** [comment]
Here's another version that also doesn't work, because I don't know what `gid` means:

```
function destroy_tile(x, y)
   for gid, tiles_i_guess in pairs(map.tileInstances) do
      for _, t in ipairs(tiles_i_guess) do
         print(t.x / 32, t.y / 32)
         if t.x == x * 32 and t.y == y * 32 and t.layer.name == "walls" then
            print("found it")
            t.batch:set(t.id, 0, 0, 0, 0, 0)
         end
      end
   end
end
```

I think the thing I need is buried inside `map.tileInstances` but I don't know what the keys or values in that table actually mean, so there's no way to find the correct batch or id.

**Comment by karai17** [comment]
Gid is global ID, a unique ID for each tile. Tile instances are organized by gid.

**Comment by karai17** [comment]
I'll add an API for this, it shouldn't be terribly difficult.

```lua
--- Swap one tile for another
-- @param table currentInstance; The instance object from map.tileInstances that we want to replace
-- @param table newTile; The tile object from map.tiles we want to use
-- @return none
function map:swapTile(currentInstance, newTile)
   -- 1) delete current tile from sprite batch
   -- 2) add new tile to sprite batch using old tile's metadata (location, mostly)
   -- 3) add new instance to instance register for new tile
   -- 4) remove old instance from register of old tile
end
```

**Comment by karai17** [comment]
Done!

**Comment by technomancy** [comment]
Nice; thanks!
