### ISSUE TITLE
[docs] convertScreenToTile -> convertScreenToWorld

### ISSUE THREAD

**Issue by danreeves** [karai17/Simple-Tiled-Implementation#97]
The docs reference Map:convertScreenToTile

**Comment by bitinn** [comment]
Furthermore, note that `convertScreenToWorld` use zero-based coordinate, while you might expect them to start with 1, and it doesn't normalize the result if you pass it a {x,y} not a multiple of tile width/height.

Which makes one wonder, why even use this api at all for orthogonal map...

**Comment by karai17** [comment]
Documentation has been updated.

It can be important to know where on a tile a point is, not just which tile, so decimal points are needed. You can simply floor the results for absolute values.
